<?php
defined('ABSPATH') || exit;
$asset = static fn(string $name): string => esc_url(audita_category_template_asset($name));
$app = 'https://app.auditainteligente.com.br/#analise-cobrancas';
$occurrences = [
 ['Seguro cartão','SEGURO CARTÃO','A descrição pode aparecer abreviada no meio dos demais itens da fatura.'],
 ['Proteção','PROTEÇÃO FINANCEIRA','Valores pequenos e recorrentes podem continuar por meses sem chamar atenção.'],
 ['Seguro LIS','SEGURO LIS','A Audita separa o lançamento para você confirmar se houve contratação.'],
 ['Seguro de vida','ITAÚ VIDA','O nome encontrado é um sinal para conferir, não uma conclusão automática.'],
 ['Descrição abreviada','ITAU SEG AP PF','A leitura assistida ajuda a localizar descrições bancárias difíceis de entender.'],
 ['Após cancelamento','A cobrança continuou','Faturas e protocolos ajudam a mostrar se o débito permaneceu depois do pedido de cancelamento.'],
];
$faqs = [
 ['Este é o caso do acordo do Itaú com o MPMG e o Idec?','Sim. O produto usa como contexto o acordo nacional relacionado a seguros cobrados sem consentimento ou mantidos após cancelamento. A análise da Audita ajuda a localizar e documentar cobranças, mas não confirma automaticamente que uma pessoa atende aos critérios do acordo.'],
 ['Quem pode pedir ressarcimento pelo acordo?','O acordo possui requisitos próprios, como prova da cobrança, registro de reclamação até 18 de dezembro de 2025 e ausência de ressarcimento anterior. Quem descobrir agora uma possível cobrança nos últimos cinco anos ainda pode reclamar, pedir cancelamento e avaliar as medidas cabíveis.'],
 ['Preciso ter todos os extratos?','Você precisa enviar ao menos uma fatura, extrato ou print para começar. Quanto maior o período documentado, mais completa pode ser a análise. Com documentos parciais, o resultado também será parcial.'],
 ['Quais arquivos posso enviar?','A plataforma aceita PDF, PNG, JPG ou JPEG, CSV e TXT, com até 12 MB por arquivo. Você pode selecionar vários documentos na mesma análise.'],
 ['O cálculo mostra quanto vou receber?','Não. O cálculo soma somente valores encontrados nos documentos e confirmados por você como não reconhecidos. Juros, correção, eventual devolução em dobro e outros pedidos dependem do caso e de avaliação jurídica.'],
 ['A Audita entra com o processo para mim?','Não. Quando aplicável, a Audita organiza o relatório, prepara uma minuta para revisão e indica os canais oficiais. A conferência e o protocolo final continuam sob responsabilidade da pessoa usuária ou de um profissional.'],
 ['Quais cartões entram na análise?','O fluxo atual é voltado a Itaú, Itaucard e referências de cartões emitidos para redes parceiras. O vínculo da marca com o banco e a existência de uma cobrança precisam ser confirmados nos documentos enviados.'],
];
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class(); ?>><?php wp_body_open(); ?><main class="page audita-landing">
<header class="header"><div class="container"><a href="/analise-cobrancas-indevidas" aria-label="Audita — início"><img src="<?= $asset('audita-oficial-branca.png') ?>" alt="Audita" class="logo" width="800" height="600"></a><nav class="nav" aria-label="Navegação principal"><a href="#caso-itau">O caso Itaú</a><a href="#como-funciona">Como funciona</a><a href="#o-que-voce-recebe">O que você recebe</a><a href="#duvidas">Dúvidas</a></nav><a class="button headerButton" href="<?= esc_url($app) ?>" data-audita-cta="header">Conferir meu Itaú</a><button class="menuButton" aria-label="Abrir menu" aria-expanded="false"><span></span><span></span><span></span></button></div></header>
<section class="hero chargeHero"><img src="<?= $asset('hero-cobrancas-indevidas.png') ?>" alt="Consumidora conferindo faturas e extratos em casa" class="heroImage"><div class="heroShade"></div><div class="container heroContent"><p class="eyebrow">Caso Itaú · cobranças de seguros sem consentimento</p><h1 class="chargeQuestion">O Itaú cobrou um seguro que você não contratou?</h1><h2 class="chargeAlert">A inclusão de seguros sem sua autorização é ILEGAL</h2><div class="chargeLegal"><p class="chargeLegalIntro">(Art. 39, I do CDC) e dá direito à devolução dos valores. Essa prática abusiva foi comprovada na Ação Civil Coletiva nº 5085307-63.2016.8.13.0024 (TJMG) para cobranças ocorridas desde 2011 até a presente data, em que o Itaú se comprometeu a ressarcir os consumidores.</p><p class="chargeEvidenceLead">Foi judicialmente confirmado na ação que os seguros abaixo foram debitados sem prévia autorização:</p><ul class="chargeInsuranceList"><li><strong>Prestamista</strong><span>Embutido em empréstimos e financiamentos</span></li><li><strong>Cartão/Bolsa Protegida, Perda e Roubo</strong><span>Tarifas mensais na fatura</span></li><li><strong>Proteção Financeira / Perda de Renda</strong><span>Cobrada para quitar faturas</span></li><li><strong>Acidentes Pessoais / Vida</strong><span>Débitos em conta ou cartão</span></li><li><strong>Tarifas e Pacotes de Terceiros</strong><span>Assistências não solicitadas</span></li></ul><p class="chargeCoverage"><strong>Abrangência citada:</strong> cartões Itaú, Itaucard e 133 parceiras, como Casas Bahia, Magalu, Ponto e Marisa.</p></div><div class="heroActions"><a class="button" href="<?= esc_url($app) ?>" data-audita-cta="hero">Verificar minhas cobranças do Itaú <span>→</span></a></div><div class="heroProof"><span>Acordo nacional divulgado pelo MPMG</span><span>Faturas e extratos</span><span>Você confirma cada cobrança</span><span>Relatório em PDF</span></div></div></section>
<section class="realityStrip"><div class="container"><strong>O caso existe. A cobrança pode estar escondida no seu histórico.</strong><span>Sem olhar os documentos, você pode nem saber quanto pagou.</span></div></section>
<section class="caseSection" id="caso-itau"><div class="container caseLayout"><div class="caseLead"><p class="kicker">O caso Itaú</p><h2>O banco assumiu obrigações de ressarcimento. Agora você precisa descobrir se foi cobrado.</h2><p>O Procon-MPMG e o Idec firmaram um acordo nacional com o Itaú sobre seguros cobrados sem consentimento ou mantidos depois do cancelamento. O caso alcança também cartões emitidos em parceria com redes varejistas.</p><a class="sourceLink" href="https://www.mpmg.mp.br/portal/menu/comunicacao/noticias/itau-vai-pagar-multas-diarias-se-descumprir-acordo-firmado-com-o-procon-mpmg-e-idec-por-cobrancas-indevidas.shtml" target="_blank" rel="noreferrer">Ver a informação oficial do MPMG ↗</a></div><div class="caseFacts"><div><strong>2011—2025</strong><span>Período de cobranças contemplado pelo acordo</span></div><div><strong>Todo o Brasil</strong><span>Consumidores do Itaú e cartões de redes parceiras</span></div><div><strong>Faturas e extratos</strong><span>Os documentos são a base para comprovar o que foi cobrado</span></div><div><strong>Cancelamento e ressarcimento</strong><span>O acordo prevê regras próprias para cada situação</span></div></div></div><p class="container caseCaution">O enquadramento no acordo depende de requisitos e provas. A análise da Audita não garante ressarcimento nem substitui avaliação jurídica.</p></section>
<section class="warning" id="o-que-procurar"><div class="container"><div class="centerHeading"><p class="kicker">Como a cobrança pode aparecer</p><h2>Procure estes sinais nas suas <em>faturas do Itaú.</em></h2><p>A Audita reconhece descrições abreviadas e padrões recorrentes. Encontrar um nome não prova irregularidade: você confirma se contratou ou não.</p></div><div class="riskGrid"><?php foreach ($occurrences as [$category,$title,$description]) : ?><article class="riskCard"><span class="riskCategory"><?= esc_html($category) ?></span><h3><?= esc_html($title) ?></h3><p><?= esc_html($description) ?></p></article><?php endforeach; ?></div><p class="disclaimer">Exemplos de descrições monitoradas pelo produto. A forma do lançamento pode variar conforme o cartão, a época e o documento.</p></div></section>
<section class="story"><div class="container storyGrid"><div class="storyImage"><img src="<?= $asset('analise-cobrancas-documentos.png') ?>" alt="Pessoa conferindo lançamentos em documentos financeiros"></div><div class="storyCopy"><p class="kicker">Cobranças pequenas. Prejuízo acumulado.</p><h2>Você pode ter pago por anos sem perceber.</h2><p>Seguros e proteções costumam aparecer em valores discretos, misturados aos demais itens. A Audita percorre seus arquivos, reúne as recorrências e preserva o documento de origem de cada lançamento.</p><div class="decisionNote"><span>O caso é do Itaú. A análise é do seu histórico.</span><p>Somente valores encontrados nos anexos e marcados por você como não reconhecidos entram no cálculo.</p></div><p class="exampleNote">A análise aponta indícios e estimativas técnicas. Ela não garante restituição, indenização ou resultado judicial.</p><a class="textLink" href="<?= esc_url($app) ?>" data-audita-cta="story">Descobrir o que foi cobrado →</a></div></div></section>
<section class="how" id="como-funciona"><div class="container howLayout"><div class="howIntro"><p class="kicker">Como recuperar o controle</p><h2>Envie o extrato.<br><em>A Audita encontra.</em><br>Você decide.</h2><p>Em poucos passos, a IA Audita transforma faturas espalhadas em uma análise clara do que foi cobrado e do que merece contestação.</p><a class="button" href="<?= esc_url($app) ?>" data-audita-cta="how_it_works">Analisar faturas e extratos →</a></div><div class="processStack"><article class="processItem"><span>Envie</span><div><h3>Suas faturas ou extratos do Itaú</h3><p>PDF, imagem, CSV ou TXT. Reúna vários meses na mesma análise para enxergar a recorrência.</p></div></article><article class="processItem processAccent"><span>Analise</span><div><h3>A Audita encontra seguros, proteções e cobranças recorrentes</h3><p>Cada ocorrência permanece ligada ao arquivo, à data e ao valor em que foi encontrada.</p></div></article><article class="processItem"><span>Confirme</span><div><h3>Diga o que você contratou — e o que não reconhece</h3><p>Você responde “reconheço”, “não reconheço” ou “não sei” para cada lançamento.</p></div></article><article class="processItem"><span>Receba</span><div><h3>Cálculo documental, relatório e próximos passos</h3><p>A Audita organiza tudo o que você precisa saber para avaliar a contestação com clareza.</p></div></article></div></div></section>
<section class="deliverables" id="o-que-voce-recebe"><div class="container deliverablesGrid"><div><p class="kicker">Tudo num só lugar</p><h2>Veja quanto foi cobrado, quando começou e onde aparece.</h2><p>A Audita organiza tudo e entrega uma análise completa e resumida do que você precisa saber para contestar com mais clareza e tranquilidade.</p></div><div class="checkList"><div><b>✓</b><span><strong>Ocorrências por arquivo</strong><small>Descrição, data, valor e documento de origem</small></span></div><div><b>✓</b><span><strong>Histórico organizado</strong><small>Visão consolidada sem duplicar lançamentos</small></span></div><div><b>✓</b><span><strong>Cálculo do valor documentado</strong><small>Somente do que você marcou como não reconhecido</small></span></div><div><b>✓</b><span><strong>Relatório técnico em PDF</strong><small>Material para revisar, consultar e compartilhar</small></span></div></div></div></section>
<section class="faq" id="duvidas"><div class="container faqGrid"><div><p class="kicker">Antes de começar</p><h2>Perguntas comuns sobre a análise.</h2></div><div><?php foreach ($faqs as $index => [$question,$answer]) : $id="audita-faq-$index"; ?><article><button type="button" data-faq aria-expanded="<?= $index===0?'true':'false' ?>" aria-controls="<?= esc_attr($id) ?>"><span><?= esc_html($question) ?></span><b><?= $index===0?'−':'+' ?></b></button><p id="<?= esc_attr($id) ?>" <?= $index===0?'':'hidden' ?>><?= esc_html($answer) ?></p></article><?php endforeach; ?></div></div></section>
<section class="finalCta"><div class="container"><img src="<?= $asset('audita-oficial-branca.png') ?>" alt="Audita" class="logo" width="800" height="600"><p>Seu histórico pode ter a resposta</p><h2>Não aceite o “sempre foi assim”.<br>Confira o que o Itaú cobrou.</h2><a class="button" href="<?= esc_url($app) ?>" data-audita-cta="final">Verificar minhas faturas agora →</a><small>O resultado depende dos documentos enviados e da sua confirmação.</small></div></section>
<article class="postContent"><div class="container"><h2><?php the_title(); ?></h2><div class="postBody"><?php the_content(); ?></div></div></article>
<footer class="footer"><div class="container"><div><img src="<?= $asset('audita-oficial-branca.png') ?>" alt="Audita" class="logo" width="800" height="600"><p>Informação clara para entender seus documentos financeiros.</p></div><div><a href="/politica-de-privacidade">Política de Privacidade</a><a href="/termos-de-uso">Termos de Uso</a><a href="mailto:contato@audita.com.br">Contato</a></div><p>© <?= esc_html(wp_date('Y')) ?> Audita. Plataforma tecnológica de auditoria documental e apoio técnico. Não substitui advogado ou Defensoria Pública.</p></div></footer><a class="mobileSticky" href="<?= esc_url($app) ?>" data-audita-cta="mobile_sticky">Conferir minhas cobranças do Itaú →</a>
</main><?php wp_footer(); ?></body></html>
