import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";
import ProductBanner from "./ProductBanner";

export const metadata: Metadata = { title: "Uma nova visão | IA Audita", robots: { index: false, follow: false }, alternates: { canonical: "/home-clara" } };
const app = "https://app.auditainteligente.com.br/";
const groups = [
  { title: "Seu dinheiro", label: "Cobranças indevidas · Dívidas bancárias", icon: "bank", services: [
    { name: "Análise de cobranças indevidas", text: "Leitura de faturas e extratos para localizar seguros e tarifas não reconhecidos, organizar valores e documentos e preparar um relatório técnico em PDF. Conheça o escopo da análise para cartões e contas Itaú.", href: "/analise-cobrancas-indevidas", action: "Conhecer a análise de cobranças" },
    { name: "Auditoria de dívidas bancárias", text: "Conferência de contratos e extratos, organização de encargos e cálculos e preparação de um Relatório Técnico de Auditoria Financeira para apoiar a renegociação. O resultado depende da documentação e da avaliação de cada caso.", href: "/servicos/dividas-bancarias", action: "Conhecer a auditoria de dívidas" },
  ] },
  { title: "Seus direitos", label: "PIS/PASEP · Isenção de IR", icon: "file-earmark-text", services: [
    { name: "Cotas antigas do PIS/PASEP", text: "Apoio a titulares e herdeiros na consulta de cotas do antigo fundo, de 1971 a 1988. Orientação para a consulta pública gratuita no REPIS, organização de documentos e acompanhamento assistido. Não se trata do abono salarial anual.", href: `${app}#pis-pasep`, action: "Ver no aplicativo" },
    { name: "Isenção e restituição de IR", text: "Organização de laudos e comprovantes para avaliar a possibilidade de isenção por moléstia grave para aposentados, pensionistas e militares na reserva ou reforma. Requisitos e períodos de restituição dependem de análise profissional.", status: "Temporariamente indisponível" },
  ] },
  { title: "Seu patrimônio", label: "Análise de vendedor · Diligência imobiliária", icon: "house", services: [
    { name: "Análise de vendedor", text: "Reunião de certidões oficiais para entender melhor quem está vendendo um imóvel, antes de assinar ou pagar. O escopo atual inclui quatro certidões do TJDFT para pessoa física no Distrito Federal.", href: "/analise-de-vendedor", action: "Conhecer a análise de vendedor" },
    { name: "Due diligence imobiliária", text: "Investigação ampliada do vendedor e do imóvel: processos, débitos, ônus, histórico de propriedade e documentação urbana ou rural. Cobertura, consultas adicionais e taxas de cartórios devem ser confirmadas antes da contratação.", href: `${app}#central-servicos`, action: "Consultar disponibilidade" },
  ] },
  { title: "Sua empresa", label: "Importação · Energia elétrica", icon: "briefcase", services: [
    { name: "Importação e otimização da TIPI", text: "Leitura de Invoice e Packing List, apoio à classificação NCM/TIPI, pesquisa de Ex-Tarifários e conferência documental antes do registro da DI/Duimp. Escopo e integrações em validação.", status: "Em preparação" },
    { name: "Auditoria de contas de luz", text: "Conferência de consumo, tarifas, tributos e somas das faturas de residências e empresas. Histórico organizado e requerimento para avaliação pela distribuidora, sem envio automático ou garantia de restituição.", status: "Disponível em piloto", href: `${app}#contas-de-luz`, action: "Ver no aplicativo" },
  ] },
  { title: "No seu dia a dia", label: "Assistente IA · Consulta de imóveis", icon: "chat-left-text", services: [
    { name: "Assistente IA Audita", text: "Converse, organize ideias e trabalhe com documentos. Apoio à leitura de PDFs e imagens, resumos, traduções, textos e identificação de cláusulas, datas e valores. Confira sempre as respostas geradas.", href: `${app}chat`, action: "Conhecer o assistente" },
    { name: "Consulta de imóveis", text: "Um ponto de partida para acessar informações imobiliárias. Canais e cobertura estão em validação; confira no aplicativo quais consultas estão disponíveis.", status: "Em homologação", href: `${app}#consulta-imoveis`, action: "Consultar disponibilidade" },
  ] },
];
// CNC/Peic, agosto de 2026: percentual entre famílias endividadas, não entre todas as famílias.
const debts = [["Cartão de crédito",85.1],["Carnês de lojas",15.8],["Crédito pessoal",13.1],["Financiamento de imóvel",9.5],["Financiamento de veículo",8.9],["Crédito consignado",7.3],["Cheque especial",3.2],["Outras dívidas",2.5]] as const;

export default function LightHome() {
  return <main className={styles.home}>
    <section className={`${styles.wrap} ${styles.hero}`}>
      <div className={styles.heroCopy}><p className={styles.eyebrow}>Inteligência a serviço das pessoas</p><h1>Informação complexa.<br/><em>Entendimento simples.</em></h1><p className={styles.lead}>Inteligência artificial, organização documental e análise técnica para transformar informações em decisões mais claras.</p><div className={styles.actions}><a className={styles.button} href="#servicos">Conheça nossas soluções</a><a className={styles.link} href="#sobre">Sobre a IA Audita</a></div></div>
      <Image className={styles.heroArt} src="/images/home-clara-marca.png" width={900} height={900} alt="" priority />
      <div className={styles.statement}><p>Tecnologia para ler. Clareza para decidir.</p><span>Mais informação.<br/>Mais possibilidades.</span></div>
    </section>
    <ProductBanner />
    <section className={`${styles.wrap} ${styles.solutions}`} id="servicos"><div><p className={styles.eyebrow}>Nossas soluções</p><h2>Diferentes necessidades.<br/><em>O mesmo cuidado<br/>com a informação.</em></h2><p className={styles.lead}>A IA Audita aplica inteligência artificial e análise técnica para organizar documentos complexos e transformar informação em clareza, para pessoas físicas e jurídicas.</p><p className={styles.hint}>Explore cada área para conhecer os serviços.</p></div><div>{groups.map(group => <details className={styles.group} key={group.title}><summary><span className={styles.icon}><Image src={`/icons/${group.icon}.svg`} width={25} height={25} alt=""/></span><span><strong>{group.title}</strong><small>{group.label}</small></span><Image className={styles.arrow} src="/icons/arrow-right.svg" width={22} height={22} alt=""/></summary><div className={styles.serviceList}>{group.services.map(service => <article key={service.name}><h3>{service.name}</h3>{service.status && <span className={styles.status}>{service.status}</span>}<p>{service.text}</p>{service.href && <Link className={styles.link} href={service.href}>{service.action}</Link>}</article>)}</div></details>)}<p className={styles.upcoming}><strong>Novas análises em desenvolvimento</strong><br/>Laudos para análise de exames e atualização de processos judiciais.</p></div></section>
    <section className={styles.financial} id="contexto-financeiro"><div className={`${styles.wrap} ${styles.split}`}><div><p className={styles.eyebrow}>Dívidas bancárias e cobranças no cartão</p><h2>Juros pesando?<br/><em>Cobrança que você<br/>não reconhece?</em></h2><p className={styles.lead}>São situações diferentes — e a IA Audita tem uma análise para cada uma. Envie seus documentos para entender os valores e os próximos passos.</p><div className={styles.productPaths}><article><h3>Entenda sua dívida. Prepare a renegociação.</h3><p>Envie os extratos desde o início do saldo devedor. A IA Audita identifica juros e encargos, confere a evolução do saldo e compara cenários com referências do Banco Central. Após a análise e a contratação, você recebe um laudo em PDF para negociar com o banco ou cobrador.</p><a className={styles.button} href={`${app}#dividas-bancarias`}>Analisar minha dívida bancária</a></article><article><h3>Confira os seguros e serviços do seu cartão.</h3><p>Nas faturas e extratos de cartões Itaú, Itaucard e parceiros, a IA Audita localiza possíveis cobranças não reconhecidas. Você confere os lançamentos, e a plataforma organiza datas, valores e documentos para o relatório técnico e a avaliação dos próximos passos.</p><Link className={styles.link} href="/analise-cobrancas-indevidas">Conhecer a análise de cobranças no cartão</Link></article></div><p className={styles.note}>A análise automática de dívidas cobre cheque especial PF/MEI e PJ identificado; outras modalidades exigem metodologia própria. A referência do Banco Central não é um teto legal. As análises dependem dos documentos e não garantem redução ou restituição. Endividamento não significa inadimplência nem comprova cobrança indevida.</p></div><figure className={styles.chart}><figcaption><h3>Tipos de endividamento das famílias</h3><p>Percentual entre famílias endividadas · Agosto de 2026</p></figcaption>{debts.map(([label,value])=><div className={styles.bar} key={label}><div><span>{label}</span><strong>{value.toLocaleString("pt-BR",{minimumFractionDigits:1})}%</strong></div><span className={styles.barTrack} role="meter" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value} aria-label={label}><span style={{width: `${value}%`}} /></span></div>)}<p className={styles.note}>Fonte: <a href="https://portaldocomercio.org.br/publicacoes_posts/pesquisa-de-endividamento-e-inadimplencia-do-consumidor-peic-agosto-2026/" className={styles.link}>CNC · Peic, agosto de 2026</a>. Seleção dos principais tipos de dívida. Uma família pode ter mais de um tipo de dívida.</p></figure></div></section>
    <section className={`${styles.wrap} ${styles.about} ${styles.split}`} id="sobre"><div><p className={styles.eyebrow}>Sobre a IA Audita</p><h2>Uma plataforma.<br/><em>Diferentes formas<br/>de ajudar.</em></h2></div><div><p className={styles.lead}>Entender documentos não deveria ser um obstáculo para tomar boas decisões.</p><p>Conectamos inteligência artificial, organização documental e análise técnica especializada para transformar informações complexas e dispersas em conhecimento claro, acessível e decisivo.</p><p>De uma negociação imobiliária à conferência de faturas, nosso compromisso é facilitar a leitura, organizar as informações e dar mais clareza aos próximos passos.</p><a className={styles.link} href={`${app}#central-servicos`}>Explore a plataforma IA Audita</a><p className={styles.note}>A análise depende dos documentos e fontes disponíveis. Não garante ausência de riscos, redução de dívidas ou ressarcimento e não substitui orientação profissional quando necessária.</p></div></section>
    <footer className={styles.footer}><div className={styles.wrap}><div className={styles.footerBrand}><Image src="/images/audita-oficial-branca.png" width={58} height={44} alt=""/><strong>IA Audita</strong><p>Inteligência para as decisões da vida.</p></div><nav aria-label="Links institucionais"><Link href="/#servicos">Nossas soluções</Link><Link href="/politica-de-privacidade">Privacidade</Link><Link href="/termos-de-uso">Termos de uso</Link></nav></div></footer>
  </main>;
}
