import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd } from "./ServiceDetails";
import s from "./services.module.css";
import d from "./BankDebtPage.module.css";

const checks = [
  ["Juros e capitalização", "Confira como os juros entram no saldo e se a periodicidade aplicada corresponde ao contrato. Capitalização não é irregular por si só: a pactuação e as regras da operação precisam ser analisadas."],
  ["Taxas e encargos", "Compare taxas contratadas, valores cobrados e referências do Banco Central para a mesma modalidade e período. Uma diferença é um ponto para investigar, não uma conclusão automática de abusividade."],
  ["Serviços não reconhecidos", "Localize seguros, tarifas, pacotes de serviços e lançamentos recorrentes para conferir contratação, autorização e eventual duplicidade."],
];

export function BankDebtPage({ page }: { page: ServicePage }) {
  return <main className={`${s.page} ${s.dark} ${d.page}`} data-service="dividas-bancarias">
    <section className={d.hero}><div className={`${s.wrap} ${s.split}`}>
      <div><p className={s.kicker}>Auditoria de débitos e juros bancários</p><h1>Sua dívida cresceu.<br/><em>Mas a conta está certa?</em></h1><p className={s.lead}>Antes de aceitar o saldo ou fechar um acordo, entenda o que você está pagando. A IA Audita organiza extratos, identifica encargos e prepara uma análise técnica para apoiar sua negociação.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#como-funciona">Entenda a análise ↓</a></div><p className={s.note}>Documentos de diferentes bancos. Escopo e modalidade confirmados no aplicativo.</p></div>
      <aside className={d.report} aria-label="Estrutura ilustrativa do relatório"><p className={s.kicker}>Da cobrança à explicação</p><h2>O saldo tem<br/>uma história.</h2><dl><div><dt>01 · Origem</dt><dd>Valor utilizado e contrato</dd></div><div><dt>02 · Evolução</dt><dd>Juros, encargos e pagamentos</dd></div><div><dt>03 · Conferência</dt><dd>Divergências e documentos de apoio</dd></div><div><dt>04 · Próximo passo</dt><dd>Relatório técnico para revisão</dd></div></dl><p className={s.note}>Estrutura ilustrativa. A análise depende dos documentos apresentados.</p></aside>
    </div></section>

    <section className={s.section} id="o-que-analisamos"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>O papel da IA Audita</p><h2>Não olhe só para o total.<br/><em>Confira o que compõe a dívida.</em></h2><p>O histórico financeiro ajuda a separar o valor utilizado dos encargos acumulados e a formular perguntas objetivas ao banco.</p></div><div className={s.cards}>{checks.map(([title,text],i)=><article className={s.card} key={title}><span className={s.cardNumber}>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className={`${s.section} ${d.band}`} id="caso-noticiado"><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>Um caso que chama atenção</p><h2>De cerca de R$ 12 mil<br/><em>a R$ 788 mil.</em></h2><p className={s.lead}>Uma reportagem de maio de 2026 relata a denúncia de um cliente do Nubank no Distrito Federal: a dívida do cartão teria atingido R$ 788 mil em quatro anos. A Secretaria do Consumidor cobrou esclarecimentos sobre juros e encargos.</p><a className={s.textLink} href="https://bncnoticias.com.br/noticia/342/divida-de-r-12-mil-vira-r-788-mil-e-cliente-denuncia-nubank" target="_blank" rel="noopener noreferrer">Ler a notícia reproduzida do Metrópoles ↗</a></div><div className={d.casePanel}><p className={s.kicker}>O que esse caso ensina</p><h3>Uma cobrança precisa ser explicada.</h3><div className={s.equation}><div><strong>R$ 12 mil</strong><small>Valor inicial aproximado noticiado</small></div><span aria-hidden="true">→</span><div><strong>R$ 788 mil</strong><small>Saldo relatado após quatro anos</small></div></div><p>Para avaliar uma evolução como essa, é necessário reconstruir o histórico, identificar taxas, pagamentos, renegociações e as regras aplicáveis a cada período.</p><p className={s.note}>Caso noticiado, não auditado pela IA Audita. A denúncia e a notificação não equivalem a uma decisão judicial nem comprovam valor recuperável.</p></div></div></section>

    <section className={s.section} id="como-funciona"><div className={s.wrap}><p className={s.kicker}>Do documento ao próximo passo</p><h2>Organize. Confira.<br/><em>Negocie com informação.</em></h2><ol className={s.steps}><li><h3>Reúna o histórico</h3><p>Separe extratos completos, contratos, faturas e comprovantes de pagamento. Identifique banco, conta e modalidade.</p></li><li><h3>Confirme o escopo</h3><p>O aplicativo verifica os documentos e informa as condições da análise. O cálculo automático atual cobre cheque especial PF/MEI e PJ identificado.</p></li><li><h3>Receba a análise</h3><p>Com documentação suficiente e contratação concluída, consulte a evolução do saldo, os encargos e a memória de cálculo do relatório técnico.</p></li><li><h3>Avalie como agir</h3><p>Use o relatório para pedir esclarecimentos, negociar ou consultar um advogado ou a Defensoria Pública sobre as medidas cabíveis.</p></li></ol></div></section>

    <section className={`${s.section} ${d.band}`} id="relatorio"><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>Informação que você pode usar</p><h2>Um relatório técnico.<br/><em>Uma base para decidir.</em></h2><p className={s.lead}>Troque um saldo sem explicação por um histórico organizado. A análise reúne os elementos disponíveis para uma revisão financeira e, quando necessária, jurídica.</p><p className={s.note}>Cartões, empréstimos e financiamentos exigem metodologia própria. A notícia acima não amplia automaticamente a cobertura do cálculo disponível.</p><div className={s.actions}><ServiceAction page={page}/></div></div><aside className={s.reportOutline}><p>O que conferir no relatório</p><ol><li><strong>Documentos e períodos</strong><span>Origem dos dados e eventuais lacunas no histórico.</span></li><li><strong>Evolução do saldo</strong><span>Lançamentos, pagamentos, juros e encargos identificados.</span></li><li><strong>Memória de cálculo</strong><span>Premissas e referências utilizadas na análise aplicável.</span></li><li><strong>Pontos para revisão</strong><span>Divergências e informações que precisam de esclarecimento.</span></li></ol></aside></div></section>

    <section className={s.section} id="seus-direitos"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Fundamentação e possibilidades</p><h2>O relatório apoia a análise.<br/><em>O direito depende do caso.</em></h2><p>Uma divergência pode justificar esclarecimentos, revisão do saldo ou avaliação de valores pagos indevidamente. Cada medida exige documentação e fundamento.</p></div><div className={s.rows}><article><span>01</span><div><h3>Revisão da cobrança</h3><p>Contrato, modalidade e período orientam a análise dos juros e encargos. A taxa média de mercado é uma referência; ultrapassá-la não comprova, isoladamente, abusividade.</p></div></article><article><span>02</span><div><h3>Restituição de valores pagos</h3><p>O art. 42, parágrafo único, do CDC prevê devolução em dobro do valor pago em excesso, com correção e juros legais, salvo engano justificável. A aplicação depende dos fatos e da jurisprudência pertinente; um saldo cobrado não é necessariamente um valor já pago.</p></div></article><article><span>03</span><div><h3>Perdas e danos</h3><p>Os arts. 186 e 927 do Código Civil fundamentam a responsabilidade por danos nas hipóteses legais. Eventual reparação exige análise da conduta, do prejuízo e do nexo causal. Não há indenização automática por toda divergência.</p></div></article></div></div></section>
    <ServiceEnd page={page} title="Antes de negociar, entenda sua dívida." text="Reúna seus documentos e confira no aplicativo como iniciar a análise." faqTitle="Dúvidas antes de começar"/>
  </main>;
}
