import Link from "next/link";
import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd } from "./ServiceDetails";
import s from "./services.module.css";

export function CertificatesPage({ page }: { page: ServicePage }) {
  return <main className={s.page} data-service="certidoes-estaduais">
    <section className={s.certHero}><div className={s.wrap}><p className={s.kicker}>Certidões estaduais · Pessoas e empresas</p><h1>Antes de confiar em um “nada consta”,<br/><em>entenda o que foi consultado.</em></h1><p className={s.lead}>Uma certidão é uma informação com origem, data e abrangência. Saiba escolher o documento, conferir sua autenticidade e interpretar o resultado para a decisão que você precisa tomar.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#leitura-da-certidao">Aprenda a ler a certidão ↓</a></div><div className={s.certPreview}><div className={s.certSide}><strong>Quem foi pesquisado?</strong>Nome, CPF ou CNPJ precisam corresponder à pessoa ou empresa da sua negociação.</div><aside className={s.certificate} aria-label="Modelo ilustrativo de leitura de uma certidão"><p>Exemplo visual · Não é documento oficial</p><h2>Certidão judicial</h2><dl><div><dt>Identificação</dt><dd>Pessoa ou empresa consultada</dd></div><div><dt>Abrangência</dt><dd>Tribunal · área · bases consultadas</dd></div><div><dt>Resultado</dt><dd>Leia também as observações</dd></div><div><dt>Validação</dt><dd>Data e código do emissor</dd></div></dl><small>O conteúdo e o formato variam conforme o tribunal.</small></aside><div className={s.certSide}><strong>O que ficou fora?</strong>Uma pesquisa estadual não reúne automaticamente Justiça Federal, Justiça do Trabalho, tributos e registros de imóveis.</div></div></div></section>


    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><div><p className={s.kicker}>O documento começa pela finalidade</p><h2>Não existe uma única certidão<br/>para todas as perguntas.</h2></div><div className={s.copy}><p>Uma contratação, uma compra de imóvel e uma exigência cadastral podem pedir documentos diferentes. Antes de emitir, confira quem solicita a certidão, de quem serão os dados e qual informação é necessária.</p><p>As opções cíveis, criminais e outras modalidades seguem critérios próprios dos tribunais. Também podem variar os graus de jurisdição, o alcance territorial e os procedimentos para pessoa física ou jurídica.</p><p>A IA Audita organiza o acesso às opções disponíveis por estado. O documento é emitido no âmbito do órgão responsável; disponibilidade, prazo e condições devem ser conferidos para cada consulta.</p></div></div></section>

    <section className={`${s.section} ${s.paper}`} id="leitura-da-certidao"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Quatro verificações essenciais</p><h2>Leia além do resultado.</h2><p>A palavra que aparece na conclusão só faz sentido depois de conferir os dados e os limites da pesquisa.</p></div><div className={s.cards}><article className={s.card}><span className={s.cardNumber}>01 · IDENTIDADE</span><h3>É a pessoa certa?</h3><p>Confira nome e identificadores. Se houver homônimo, use os dados e o procedimento do tribunal para esclarecer a correspondência antes de atribuir um processo a alguém.</p></article><article className={s.card}><span className={s.cardNumber}>02 · ALCANCE</span><h3>Qual foi a pesquisa?</h3><p>Leia órgão, área e bases abrangidas. Um documento de uma UF não equivale a uma consulta nacional, e uma certidão cível não substitui todas as modalidades.</p></article><article className={s.card}><span className={s.cardNumber}>03 · DATA</span><h3>Serve para esta ocasião?</h3><p>Confira a emissão, eventual validade e a exigência de quem receberá o documento. O contexto pode exigir uma nova consulta mais perto da assinatura.</p></article></div><div className={s.freeCallout}><strong>04 · Autenticidade</strong><p>Use o código e o endereço de validação do emissor. Compare os dados retornados com o arquivo recebido e preserve o original. Uma imagem recortada pode omitir observações importantes.</p></div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.sectionIntro}><p className={s.kicker}>Interpretar para decidir</p><h2>Três situações.<br/>Três cuidados diferentes.</h2></div><div className={s.resultCards}><article><span className={s.label}><i className={s.dot} aria-hidden="true"/>Resultado negativo</span><h3>Confira os limites.</h3><p>A certidão atende aos critérios de resultado negativo daquela modalidade. Isso não elimina fatos fora da abrangência nem substitui os demais documentos da negociação.</p></article><article><span className={s.label}><i className={`${s.dot} ${s.dotAmber}`} aria-hidden="true"/>Apontamento</span><h3>Busque o contexto.</h3><p>Identifique a parte, o assunto e a situação do processo. Um registro, isoladamente, não prova dívida exigível, condenação ou impedimento para vender.</p></article><article><span className={s.label}><i className={`${s.dot} ${s.dotBlue}`} aria-hidden="true"/>Pendência de emissão</span><h3>Esclareça os dados.</h3><p>Verifique se faltam identificadores, se há dúvida de identidade ou se o emissor exige atendimento complementar. Pendência não é sinônimo de resultado positivo.</p></article></div></section>

    <section className={`${s.section} ${s.dark}`} id="exemplos"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Na negociação, na prática</p><h2>O documento informa.<br/>O contexto orienta.</h2><p>Situações fictícias para mostrar como ler os resultados, sem atribuir casos a pessoas reais.</p></div><div className={s.casePair}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo 01 · Compra de imóvel</span><h3>“A certidão deu negativa. Posso assinar?”</h3><p>Uma compradora recebe a certidão cível estadual do vendedor. Os dados estão corretos e a autenticidade foi validada.</p><h4>O que já se sabe</h4><p>Há um resultado daquela pesquisa, na data indicada. Ainda é necessário conferir se a abrangência atende à negociação e quais outros documentos foram exigidos.</p><h4>O que vem depois</h4><p>Verificar a matrícula do imóvel e os demais registros pertinentes. A certidão do vendedor é uma parte da análise, não uma garantia completa sobre a compra.</p></article><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo 02 · Nome semelhante</span><h3>Um apontamento aparece. A identidade precisa ser confirmada.</h3><p>O documento registra uma situação que exige esclarecimento, e há uma pessoa com nome semelhante. O vendedor também participa de uma empresa.</p><h4>São duas perguntas distintas</h4><p>Primeiro, verificar se o apontamento corresponde ao vendedor. Depois, avaliar se os vínculos empresariais justificam consultas de CNPJ e análise complementar.</p><h4>O que vem depois</h4><p>Reunir a documentação e buscar contexto dos registros. Uma obrigação da empresa não deve ser atribuída automaticamente ao sócio.</p></article></div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.sectionIntro}><p className={s.kicker}>Monte o conjunto adequado</p><h2>Documentos complementares<br/>não são documentos iguais.</h2></div><div className={s.tableBox} role="region" aria-label="Abrangência dos documentos" tabIndex={0}><table><caption>O que cada consulta ajuda a esclarecer</caption><thead><tr><th scope="col">Documento</th><th scope="col">Objeto da consulta</th><th scope="col">Cuidado ao interpretar</th></tr></thead><tbody><tr><th scope="row">Judicial estadual</th><td>Pesquisa no âmbito e na modalidade definidos pelo tribunal.</td><td>Não pressupor cobertura de todas as UFs ou áreas.</td></tr><tr><th scope="row">Federal ou trabalhista</th><td>Informações nos órgãos e sistemas correspondentes.</td><td>Não presumir que constam da certidão estadual.</td></tr><tr><th scope="row">Fiscal</th><td>Situação tributária perante o órgão competente.</td><td>Não confundir regularidade fiscal com inexistência de processos.</td></tr><tr><th scope="row">Matrícula do imóvel</th><td>Registros, titularidade e informações do registro imobiliário.</td><td>Não substituir pela pesquisa judicial do proprietário.</td></tr></tbody></table></div><aside className={s.sellerLink}><div><p className={s.kicker} style={{color:'#46d0ff'}}>Vai comprar um imóvel?</p><h3>Conecte as certidões à análise do vendedor.</h3></div><div><p>Vínculos com empresas e registros de diferentes âmbitos podem exigir uma avaliação mais ampla. Conheça o serviço que organiza esses pontos em contexto.</p><Link className={s.textLink} href="/analise-de-vendedor">Conhecer a análise de vendedor →</Link></div></aside></section>

    <section className={`${s.section} ${s.paper}`} id="como-funciona"><div className={s.wrap}><div className={s.split}><div><p className={s.kicker}>Antes de solicitar</p><h2>Tenha a identificação.<br/>Defina a finalidade.</h2><p className={s.lead}>Pessoa física ou jurídica, UF e modalidade são o início. Cada tribunal pode pedir informações adicionais.</p></div><ul className={s.checklist}><li><strong>Dados completos e conferidos</strong>Nome, CPF ou CNPJ e demais identificadores exigidos pelo emissor.</li><li><strong>Finalidade e localidade</strong>Quem receberá a certidão, quais documentos foram pedidos e para qual território.</li><li><strong>Arquivos e protocolos anteriores</strong>Resultados já obtidos, pendências e exigências de complementação.</li></ul></div><ol className={s.steps}><li><h3>Selecione</h3><p>Encontre a UF e a modalidade disponível para sua finalidade.</p></li><li><h3>Informe</h3><p>Confira os dados antes de seguir o pedido.</p></li><li><h3>Acompanhe</h3><p>Observe o prazo e as orientações do emissor.</p></li><li><h3>Valide</h3><p>Confira autenticidade e abrangência antes de usar o documento.</p></li></ol></div></section>
    <ServiceEnd page={page} faqTitle="Dúvidas antes de pedir uma certidão?" title="A certidão certa começa com a pergunta certa." text="Escolha o estado, confira as modalidades disponíveis e organize a documentação para a finalidade que você precisa."/>
  </main>;
}
