import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd, ServiceHeroPhoto } from "./ServiceDetails";
import s from "./services.module.css";

export function EnergyPage({ page }: { page: ServicePage }) {
  return <main className={s.page} data-service="revisao-contas-de-luz">
    <section className={`${s.energyHero} ${s.photoHero}`}><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>Contas de luz · Auditoria documental</p><h1>Você vê o total.<br/><em>Vamos entender cada parte da conta.</em></h1><p className={s.lead}>Consumo, tarifas, tributos e ajustes podem mudar o valor da sua fatura. A proposta da IA Audita é organizar o histórico e apontar o que precisa ser esclarecido — em casa ou na empresa.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#por-dentro-da-conta">Ler a conta por partes ↓</a></div></div><ServiceHeroPhoto name="energia" alt="Cena ilustrativa de uma casa com iluminação acolhedora ao anoitecer." title="Energia para a vida. Clareza para a sua conta."/></div></section>


    <section className={`${s.wrap} ${s.section}`} id="por-dentro-da-conta"><div className={s.split}><div className={s.sectionIntro}><p className={s.kicker}>Uma fatura, várias perguntas</p><h2>Antes de contestar,<br/>localize o que mudou.</h2><p>O total aponta a diferença. O detalhamento ajuda a explicar sua origem e a formular uma dúvida objetiva para a distribuidora.</p></div><aside className={s.bill} aria-label="Composição de uma conta fictícia"><div className={s.billHeader}><span>LEITURA DA FATURA</span><span>Exemplo didático</span></div><h2>De onde vem o total?</h2><dl><div><dt>Energia e distribuição</dt><dd>R$ 210,00</dd></div><div><dt>Tributos</dt><dd>R$ 55,00</dd></div><div><dt>Iluminação pública</dt><dd>R$ 25,00</dd></div><div><dt>Outros lançamentos</dt><dd>R$ 10,00</dd></div><div className={s.billTotal}><dt>Total ilustrativo</dt><dd>R$ 300,00</dd></div></dl><small>Valores fictícios, separados apenas para mostrar a composição. Não reproduzem tarifas, alíquotas ou modelo de uma distribuidora.</small></aside></div><div className={s.billAnatomy}><span>01</span><h3>Consumo e período</h3><p>Compare kWh, leituras e dias faturados. Uma conta de 35 dias não deve ser comparada com outra de 30 dias apenas pelo total. Confira se houve mudança no uso do imóvel ou no registro de medição.</p></div><div className={s.billAnatomy}><span>02</span><h3>Tarifas e bandeiras</h3><p>Mesmo com consumo parecido, preços e componentes aplicáveis ao período podem alterar o valor. Identifique a referência usada e evite interpretar todo aumento como cobrança irregular.</p></div><div className={s.billAnatomy}><span>03</span><h3>Tributos e contribuições</h3><p>Veja como os valores são identificados e quais bases são informadas. A simples presença de ICMS, PIS/Cofins ou contribuição de iluminação pública não demonstra erro.</p></div><div className={s.billAnatomy}><span>04</span><h3>Ajustes e outros lançamentos</h3><p>Serviços, multas, parcelas e compensações precisam ser associados a uma origem. Verifique competência, descrição e documentos antes de concluir que houve repetição ou cobrança sem fundamento.</p></div></section>

    <section className={`${s.section} ${s.paper}`} id="exemplos"><div className={`${s.wrap} ${s.split}`}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo fictício 01 · Residência</span><h2>Mais kWh.<br/>A mesma média diária.</h2><p style={{marginTop:24}}>Uma família percebe que o consumo foi de 240 para 280 kWh. Antes de procurar um erro, compara o período de cada conta.</p><div className={s.consumption}><div><small>Período A · 30 dias</small><strong>240 kWh</strong><small>240 ÷ 30 = 8 kWh/dia</small></div><div><small>Período B · 35 dias</small><strong>280 kWh</strong><small>280 ÷ 35 = 8 kWh/dia</small></div></div><p>A média de 8 kWh por dia é igual nos dois períodos. Isso explica a diferença de quantidade no exemplo, mas a variação em reais ainda exige conferir tarifas e demais componentes.</p></article><div><p className={s.kicker}>O histórico dá contexto</p><h3>O que vale comparar?</h3><ul className={s.checklist} style={{marginTop:25}}><li><strong>Dias e leituras</strong>As datas e medições correspondem ao intervalo informado?</li><li><strong>Rotina do imóvel</strong>Houve mais pessoas, uso de equipamentos ou alteração de atividade?</li><li><strong>Preço e composição</strong>Quais tarifas e lançamentos foram usados em cada período?</li><li><strong>Informações da distribuidora</strong>Há estimativas, ajustes ou respostas anteriores que expliquem a diferença?</li></ul><p className={s.note}>A comparação não substitui a verificação da medição quando houver dúvida. Ela ajuda a definir o que perguntar e quais registros apresentar.</p></div></div></section>

    <section className={`${s.section} ${s.dark}`}><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>Tributos · Entenda a diferença</p><h2>Créditos na tarifa<br/>e cobranças individuais<br/><em>seguem caminhos diferentes.</em></h2><p className={s.lead}>Uma notícia sobre devolução ao conjunto de consumidores não comprova um valor individual para saque.</p></div><div className={s.copy}><h3>O que a Lei 14.385/2022 trata</h3><p>A lei disciplina a destinação aos consumidores de valores relacionados à exclusão do ICMS da base de PIS/Cofins, recuperados pelas distribuidoras, com atuação da ANEEL nos processos tarifários.</p><h3>O que precisa de análise própria</h3><p>Uma cobrança questionada na sua fatura exige identificar lançamento, período, documentos e fundamento. O valor mensal da conta não garante recuperação, e não se deve prometer genericamente dez anos de ICMS.</p><h3>E TUST e TUSD?</h3><p>O Tema 986 do STJ trata da inclusão dessas tarifas na base de cálculo do ICMS, com regras de modulação. A presença delas na fatura não comprova, por si só, um crédito a receber.</p><a className={s.textLink} href="https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/lei/l14385.htm">Ler a Lei 14.385/2022 ↗</a></div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo fictício 02 · Empresa</span><h2>O mesmo “ajuste”<br/>apareceu duas vezes.</h2><p style={{marginTop:24}}>Uma empresa encontra a mesma descrição em duas contas e acredita que pagou em duplicidade. Há um comprovante de pagamento, mas a referência do ajuste não está clara.</p><h4>O que precisa ser conciliado</h4><p>Descrição, competência, parcela e compensações. Dois lançamentos com o mesmo nome podem ter origens diferentes. Da mesma forma, um pagamento pode estar associado a apenas uma das faturas.</p><h4>Como preparar a revisão</h4><p>Reunir as duas contas completas, o comprovante e a resposta da distribuidora sobre a origem do ajuste. Se a duplicidade for comprovada, avaliar o procedimento de correção aplicável.</p></article><div className={s.copy}><p className={s.kicker}>No ambiente empresarial</p><h3>A operação também ajuda a explicar a conta.</h3><p>Horários de produção, equipamentos e mudanças de atividade podem influenciar o consumo. Conforme a modalidade de fornecimento, demanda contratada e outros componentes exigem leitura específica.</p><p>Por isso, além das faturas, contratos e registros pertinentes podem ser necessários. Não aplique a uma unidade empresarial a mesma interpretação de uma residência sem conferir as condições de fornecimento.</p><p>O piloto deve ter seu escopo confirmado para a unidade consumidora antes de qualquer contratação.</p></div></div></section>

    <section className={`${s.section} ${s.paper}`} id="como-funciona"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Uma revisão começa com evidências</p><h2>Da pasta de faturas<br/>à pergunta bem fundamentada.</h2></div><ol className={s.steps}><li><h3>Escolha o período</h3><p>Identifique a unidade e a cobrança ou variação que deseja conferir.</p></li><li><h3>Reúna os registros</h3><p>Separe contas completas, pagamentos, contratos pertinentes e protocolos.</p></li><li><h3>Compare os itens</h3><p>Organize consumo, dias, tarifas e ajustes para localizar a diferença.</p></li><li><h3>Acompanhe a resposta</h3><p>Apresente a questão no canal competente e preserve os comprovantes do atendimento.</p></li></ol><div className={s.freeCallout}><strong>O que a análise pretende entregar</strong><p>Um histórico organizado e pontos de atenção documentados para esclarecer com a distribuidora ou avaliar com apoio especializado. A revisão não suspende vencimentos e não equivale a reconhecimento de crédito.</p></div></div></section>
    <ServiceEnd page={page} faqTitle="Dúvidas que aparecem junto com a fatura." title="Sua conta merece uma explicação que vá além do total." text="Organize o histórico da unidade consumidora e consulte o escopo do piloto. O primeiro objetivo é entender o que foi cobrado e o que precisa ser esclarecido."/>
  </main>;
}
