import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd, ServiceHeroPhoto } from "./ServiceDetails";
import s from "./services.module.css";

export function FinancialReportPage({ page }: { page: ServicePage }) {
  return <main className={s.page} data-service="laudos-de-processos-judiciais">
    <section className={`${s.financeHero} ${s.dark} ${s.photoHero}`}><div className={s.wrap}><div className={s.photoGrid}><div><p className={s.kicker}>Relatório de Atualização Financeira</p><h1>Atualize valores e gere<br/><em>relatórios de análise financeira.</em></h1><p className={s.lead}>A IA Audita reúne auditoria financeira, análise de documentos jurídicos e cálculos judiciais para apoiar o recálculo, a atualização monetária e a conferência de débitos. A proposta do módulo é gerar laudos e relatórios técnicos com índices oficiais, juros, encargos aplicáveis e memória de cálculo rastreável, para revisão e apoio à atuação do profissional responsável.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#memoria-de-calculo">Ver o exemplo de cálculo ↓</a></div></div><ServiceHeroPhoto name="laudos" alt="Cena ilustrativa de um profissional revisando relatórios financeiros com uma calculadora e documentos." title="Precisão nos detalhes. Clareza em cada decisão."/></div></div></section>


    <section className={`${s.section} ${s.dark}`}><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Estrutura prevista do módulo</p><h2>Do valor original<br/><em>ao relatório completo.</em></h2><p>Uma apresentação executiva para entender o total e um quadro analítico para conferir como ele foi formado.</p></div><div className={s.cards}><article className={s.card}><span className={s.cardNumber}>01 · IDENTIFICAÇÃO</span><h3>Contexto do processo ou da obrigação.</h3><p>Partes, número do processo, vara ou órgão, quando aplicáveis, além dos documentos de origem e da data-base da atualização.</p></article><article className={s.card}><span className={s.cardNumber}>02 · CRITÉRIOS DO CÁLCULO</span><h3>Índices, juros e períodos visíveis.</h3><p>Indicação da tabela ou do índice aplicável, como IPCA-E, INPC ou Selic, conforme os critérios do caso. Taxas, marcos iniciais e abatimentos precisam ser conferidos antes do uso.</p></article><article className={s.card}><span className={s.cardNumber}>03 · RELATÓRIO VISUAL</span><h3>Resumo executivo e quadro analítico.</h3><p>Visão dos componentes do saldo, subtotais e total atualizado, acompanhada da memória por parcela para rastrear principal, correção, juros e pagamentos.</p></article></div><p className={s.note}>Recursos apresentados como proposta do módulo. O tempo de geração depende dos documentos e da complexidade do cálculo; os resultados precisam de revisão pelo responsável.</p></div></section>

    <section className={`${s.heroSupport} ${s.dark}`}><div className={s.wrap}><aside className={s.ledger} aria-label="Resumo do relatório de referência"><div className={s.ledgerBar}><span>RELATÓRIO DE REFERÊNCIA · EXEMPLO 01</span><span>Atualização em 10/08/2026</span></div><div className={s.ledgerGrid}><div><small>Valor-base homologado no relatório</small><strong>R$ 81.037,92</strong></div><div><small>Subtotal atualizado</small><strong>R$ 101.792,54</strong></div><div><small>Honorários de 10%</small><strong>R$ 10.179,25</strong></div><div><small>Total informado</small><strong>R$ 111.971,80</strong></div></div><p>Valores reproduzidos do relatório fornecido, sem identificação das partes. Critérios específicos desse exemplo, sujeitos à conferência dos documentos de origem. Arredondamento explicado na memória abaixo.</p></aside></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><div><p className={s.kicker}>O documento antes da fórmula</p><h2>Qual valor?<br/>Desde quando?<br/>Segundo qual regra?</h2><p className={s.lead}>Essas três perguntas definem o ponto de partida. Um número preciso, calculado com a regra errada, continua sendo um resultado inadequado.</p></div><div className={s.copy}><p>A atualização financeira depende do título, da decisão, do contrato ou de outra origem da obrigação. Esses documentos ajudam a definir principal, datas e componentes da conta.</p><p>Os marcos de correção monetária e juros podem ser diferentes. Parcelas podem vencer em momentos distintos. Pagamentos parciais precisam ser registrados para que o saldo não inclua valores já quitados.</p><p>A proposta da IA Audita é organizar essas informações em um relatório revisável. O módulo está em desenvolvimento: ainda não há recebimento de documentos, solicitação de cálculo ou entrega por este serviço.</p></div></div></section>

    <section className={`${s.section} ${s.paper}`}><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Critérios que precisam ficar visíveis</p><h2>A conta deve mostrar<br/>mais do que o resultado.</h2></div><div className={s.tableBox} role="region" aria-label="Parâmetros da atualização financeira" tabIndex={0}><table><caption>O que conferir antes de calcular</caption><thead><tr><th scope="col">Componente</th><th scope="col">Pergunta essencial</th><th scope="col">Por que importa</th></tr></thead><tbody><tr><th scope="row">Principal</th><td>Qual é o valor original e sua origem?</td><td>Evita usar um saldo já atualizado como se fosse a base original.</td></tr><tr><th scope="row">Datas</th><td>Quando cada incidência começa e qual é a data-base?</td><td>Define o período de atualização de cada parcela.</td></tr><tr><th scope="row">Correção</th><td>Qual índice ou tabela se aplica ao caso?</td><td>Índices diferentes não são escolhas livres para aumentar o total.</td></tr><tr><th scope="row">Juros</th><td>Qual taxa, regime e base foram determinados?</td><td>Impede usar uma taxa universal ou duplicar componentes.</td></tr><tr><th scope="row">Abatimentos</th><td>Quanto foi pago e em qual data?</td><td>Permite examinar o saldo restante segundo o critério adequado.</td></tr><tr><th scope="row">Honorários e custas</th><td>Há fundamento e base definidos?</td><td>Separa acessórios cabíveis de percentuais apenas presumidos.</td></tr></tbody></table></div><p className={s.note}>IPCA-E, INPC, Selic e tabelas judiciais têm aplicações distintas. É necessário conferir o regime vigente e a determinação do caso. Não some automaticamente juros e correção quando o critério já reúne esses componentes.</p></div></section>

    <section className={`${s.wrap} ${s.section}`} id="memoria-de-calculo"><div className={s.split}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo 01 · Relatório de referência</span><h2>De R$ 81.037,92<br/>a R$ 111.971,80.<br/><em>Cada componente explicado.</em></h2><p style={{marginTop:25}}>O relatório enviado parte de um débito informado como homologado em 13/02/2025 e apresenta a atualização para 10/08/2026. O quadro separa principal, correção monetária, juros, honorários e total consolidado.</p><p>Para esse exemplo, o documento adota correção acumulada de 6,45%, juros de 1% ao mês por 18 meses sobre o principal corrigido e honorários de 10%. Esses parâmetros foram reproduzidos do material, não validados como regra geral do TJRJ ou de qualquer processo.</p><p>Datas, índices, contagem do período e cabimento dos encargos precisam ser confirmados na decisão e nos documentos do caso. Nomes, número do processo e código de autenticação foram omitidos.</p></article><div className={s.rows}><article><span>01</span><div><h3>Correção monetária: R$ 5.226,95</h3><p>R$ 81.037,92 × 6,45%. O principal corrigido apresentado no relatório é de R$ 86.264,87.</p></div></article><article><span>02</span><div><h3>Juros de mora: R$ 15.527,68</h3><p>O exemplo aplica 18% ao principal corrigido, correspondentes aos 18 meses adotados pelo documento. O subtotal informado, antes dos honorários, é de R$ 101.792,54.</p></div></article><article><span>03</span><div><h3>Honorários: R$ 10.179,25</h3><p>O relatório aplica 10% sobre o subtotal atualizado. A incidência e a base dos honorários dependem dos critérios do processo.</p></div></article><article><span>04</span><div><h3>Total consolidado: R$ 111.971,80</h3><p>O valor final é compatível com o cálculo sem arredondar as etapas intermediárias: R$ 81.037,92 × 1,0645 × 1,18 × 1,10 = R$ 111.971,79586032, arredondado para centavos.</p></div></article></div></div><p className={s.note}>Arredondamento: a soma das rubricas já arredondadas pode diferir em R$ 0,01. Por exemplo, R$ 101.792,54 + R$ 10.179,25 = R$ 111.971,79. O total de R$ 111.971,80 pressupõe manter a precisão intermediária até o fechamento; a memória definitiva deve explicitar esse critério.</p></section>

    <section className={`${s.section} ${s.dark}`} id="exemplos"><div className={`${s.wrap} ${s.split}`}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo fictício 02 · Parcelas e pagamento</span><h2>Três vencimentos.<br/>Um pagamento parcial.<br/><em>Uma única soma não resolve.</em></h2><p style={{marginTop:25}}>Uma planilha reúne três parcelas em um principal único. Elas venceram em datas diferentes e houve um pagamento depois do segundo vencimento.</p></article><div className={s.copy}><h3>O risco de partir apenas da soma</h3><p>Atualizar todo o valor desde o primeiro vencimento pode atribuir tempo de incidência indevido às parcelas posteriores. Ignorar o pagamento também pode aumentar artificialmente o saldo.</p><h3>O que precisa ser reconstruído</h3><p>Uma linha por parcela, com valor original e datas, e o registro do pagamento com seu comprovante. A forma de abatimento deve ser definida conforme o caso.</p><h3>Como o relatório ajuda</h3><p>A memória por item permite localizar onde cada valor entrou, qual período foi considerado e como o saldo foi formado. O responsável consegue revisar uma premissa sem depender apenas do total final.</p></div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.sectionIntro}><p className={s.kicker}>Duas entradas previstas</p><h2>Da decisão ou da planilha.<br/>Sempre com conferência.</h2><p>O módulo está sendo preparado para organizar informações documentais e valores estruturados. Os formatos e modelos serão confirmados quando houver disponibilização.</p></div><div className={s.pathway}><article style={{background:'#f1f7fa'}}><span className={s.label}>Caminho documental</span><h3>Decisão, contrato e comprovantes.</h3><p>O documento deve permitir identificar a obrigação e os critérios. Arquivos complementares podem ser necessários para parcelas, pagamentos ou mudanças posteriores.</p><ul><li>Texto completo e legível da regra aplicável.</li><li>Valores relacionados aos respectivos documentos.</li><li>Lacunas identificadas antes do cálculo.</li></ul><p>Uma decisão em PDF nem sempre contém todos os dados financeiros necessários.</p></article><article style={{background:'#f1f7fa'}}><span className={s.label}>Caminho estruturado</span><h3>Valores organizados por parcela.</h3><p>A planilha prevista deve separar rubrica, valor original e datas, além dos registros necessários à conferência de pagamentos e abatimentos.</p><ul><li>Uma obrigação ou parcela por linha.</li><li>Marcos de incidência e data-base claros.</li><li>Conciliação com os documentos de origem.</li></ul><p>Uma planilha preenchida não dispensa a validação dos critérios escolhidos.</p></article></div></section>

    <section className={`${s.section} ${s.paper}`} id="como-funciona"><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>A entrega proposta</p><h2>Uma memória para ler,<br/>revisar e discutir.</h2><p className={s.lead}>O relatório em PDF previsto reúne resumo, premissas e evolução dos valores. Sua utilidade está em permitir conferir a conta, e não apenas exibir um total.</p><div className={s.copy}><h3>O uso continua com o responsável pelo caso.</h3><p>O documento não movimenta os autos, não realiza bloqueio pelo Sisbajud e não garante aceitação judicial. Protocolo, prazos e providências permanecem com os profissionais e canais responsáveis.</p><p>Antes da disponibilização do módulo, não envie peças ou dados do processo por esta página.</p></div></div><aside className={s.reportOutline} aria-label="Estrutura prevista do relatório"><p>Relatório · Estrutura prevista</p><ol><li><strong>Identificação e data-base</strong><span>Origem da obrigação e referência temporal do cálculo.</span></li><li><strong>Premissas e fontes</strong><span>Índices, taxas, períodos e bases utilizados.</span></li><li><strong>Memória por parcela</strong><span>Principal, incidências e abatimentos documentados.</span></li><li><strong>Resumo dos componentes</strong><span>Valores separados e composição do total.</span></li><li><strong>Pontos para revisão</strong><span>Informações incompletas e critérios a esclarecer.</span></li></ol></aside></div></section>
    <ServiceEnd page={page} faqTitle="Perguntas antes de atualizar os valores." title="Entender a evolução do valor começa por entender a regra." text="Conheça os serviços disponíveis enquanto o Relatório de Atualização Financeira é preparado. Escopo, formatos e condições serão informados antes da abertura de solicitações."/>
  </main>;
}
