import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd, ServiceHeroPhoto } from "./ServiceDetails";
import s from "./services.module.css";

export function FinancialReportPage({ page }: { page: ServicePage }) {
  return <main className={s.page} data-service="laudos-de-processos-judiciais">
    <section className={`${s.financeHero} ${s.dark} ${s.photoHero}`}><div className={s.wrap}><div className={s.photoGrid}><div><p className={s.kicker}>Relatório de Atualização Financeira</p><h1>Cansado de decifrar decisões judiciais?<br/><em>Uma leitura mais clara está em preparação.</em></h1><p className={s.lead}>A proposta da IA Audita Jurídica é organizar despachos, decisões e sentenças em linguagem compreensível para apoiar a conversa com o profissional responsável pelo caso. O módulo ainda não recebe documentos.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#memoria-de-calculo">Ver o exemplo de cálculo ↓</a></div></div><ServiceHeroPhoto name="laudos" alt="Cena ilustrativa de um profissional revisando relatórios financeiros com uma calculadora e documentos." title="Precisão nos detalhes. Clareza em cada decisão."/></div></div></section>


    <section className={`${s.heroSupport} ${s.dark}`}><div className={s.wrap}><aside className={s.ledger} aria-label="Resumo de cálculo fictício"><div className={s.ledgerBar}><span>MEMÓRIA DE CÁLCULO · EXEMPLO DIDÁTICO</span><span>Hipóteses explicadas abaixo</span></div><div className={s.ledgerGrid}><div><small>Principal</small><strong>R$ 10.000</strong></div><div><small>Correção suposta</small><strong>+ R$ 200</strong></div><div><small>Juros supostos</small><strong>+ R$ 100</strong></div><div><small>Total ilustrativo</small><strong>R$ 10.300</strong></div></div><p>Exemplo fictício, sem honorários, custas ou pagamentos. Não representa cálculo de um processo real nem parâmetros a aplicar a qualquer obrigação.</p></aside></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><div><p className={s.kicker}>O documento antes da fórmula</p><h2>Qual valor?<br/>Desde quando?<br/>Segundo qual regra?</h2><p className={s.lead}>Essas três perguntas definem o ponto de partida. Um número preciso, calculado com a regra errada, continua sendo um resultado inadequado.</p></div><div className={s.copy}><p>A atualização financeira depende do título, da decisão, do contrato ou de outra origem da obrigação. Esses documentos ajudam a definir principal, datas e componentes da conta.</p><p>Os marcos de correção monetária e juros podem ser diferentes. Parcelas podem vencer em momentos distintos. Pagamentos parciais precisam ser registrados para que o saldo não inclua valores já quitados.</p><p>A proposta da IA Audita é organizar essas informações em um relatório revisável. O módulo está em desenvolvimento: ainda não há recebimento de documentos, solicitação de cálculo ou entrega por este serviço.</p></div></div></section>

    <section className={`${s.section} ${s.paper}`}><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Critérios que precisam ficar visíveis</p><h2>A conta deve mostrar<br/>mais do que o resultado.</h2></div><div className={s.tableBox} role="region" aria-label="Parâmetros da atualização financeira" tabIndex={0}><table><caption>O que conferir antes de calcular</caption><thead><tr><th scope="col">Componente</th><th scope="col">Pergunta essencial</th><th scope="col">Por que importa</th></tr></thead><tbody><tr><th scope="row">Principal</th><td>Qual é o valor original e sua origem?</td><td>Evita usar um saldo já atualizado como se fosse a base original.</td></tr><tr><th scope="row">Datas</th><td>Quando cada incidência começa e qual é a data-base?</td><td>Define o período de atualização de cada parcela.</td></tr><tr><th scope="row">Correção</th><td>Qual índice ou tabela se aplica ao caso?</td><td>Índices diferentes não são escolhas livres para aumentar o total.</td></tr><tr><th scope="row">Juros</th><td>Qual taxa, regime e base foram determinados?</td><td>Impede usar uma taxa universal ou duplicar componentes.</td></tr><tr><th scope="row">Abatimentos</th><td>Quanto foi pago e em qual data?</td><td>Permite examinar o saldo restante segundo o critério adequado.</td></tr><tr><th scope="row">Honorários e custas</th><td>Há fundamento e base definidos?</td><td>Separa acessórios cabíveis de percentuais apenas presumidos.</td></tr></tbody></table></div><p className={s.note}>IPCA-E, INPC, Selic e tabelas judiciais têm aplicações distintas. É necessário conferir o regime vigente e a determinação do caso. Não some automaticamente juros e correção quando o critério já reúne esses componentes.</p></div></section>

    <section className={`${s.wrap} ${s.section}`} id="memoria-de-calculo"><div className={s.split}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo fictício 01 · Entendendo a memória</span><h2>Como R$ 10.000<br/>viram R$ 10.300<br/>nesta simulação?</h2><p style={{marginTop:25}}>Para explicar a lógica, adotamos um fator de correção inventado de 1,02 e juros simples de 0,5% ao mês por dois meses, sobre o principal original.</p><p>São hipóteses didáticas. Não foram extraídas de uma tabela real ou de uma decisão e não indicam o tratamento de um processo específico.</p></article><div className={s.rows}><article><span>01</span><div><h3>Correção: R$ 200</h3><p>R$ 10.000 × (1,02 − 1) = R$ 200. O fator suposto corresponde a 2% no intervalo ilustrativo.</p></div></article><article><span>02</span><div><h3>Juros: R$ 100</h3><p>R$ 10.000 × 0,005 × 2 = R$ 100. Neste exemplo, os juros são simples e incidem somente sobre o principal original.</p></div></article><article><span>03</span><div><h3>Total: R$ 10.300</h3><p>R$ 10.000 + R$ 200 + R$ 100. Não há honorários, custas ou abatimentos incluídos nesta hipótese.</p></div></article></div></div></section>

    <section className={`${s.section} ${s.dark}`} id="exemplos"><div className={`${s.wrap} ${s.split}`}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo fictício 02 · Parcelas e pagamento</span><h2>Três vencimentos.<br/>Um pagamento parcial.<br/><em>Uma única soma não resolve.</em></h2><p style={{marginTop:25}}>Uma planilha reúne três parcelas em um principal único. Elas venceram em datas diferentes e houve um pagamento depois do segundo vencimento.</p></article><div className={s.copy}><h3>O risco de partir apenas da soma</h3><p>Atualizar todo o valor desde o primeiro vencimento pode atribuir tempo de incidência indevido às parcelas posteriores. Ignorar o pagamento também pode aumentar artificialmente o saldo.</p><h3>O que precisa ser reconstruído</h3><p>Uma linha por parcela, com valor original e datas, e o registro do pagamento com seu comprovante. A forma de abatimento deve ser definida conforme o caso.</p><h3>Como o relatório ajuda</h3><p>A memória por item permite localizar onde cada valor entrou, qual período foi considerado e como o saldo foi formado. O responsável consegue revisar uma premissa sem depender apenas do total final.</p></div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.sectionIntro}><p className={s.kicker}>Duas entradas previstas</p><h2>Da decisão ou da planilha.<br/>Sempre com conferência.</h2><p>O módulo está sendo preparado para organizar informações documentais e valores estruturados. Os formatos e modelos serão confirmados quando houver disponibilização.</p></div><div className={s.pathway}><article style={{background:'#f1f7fa'}}><span className={s.label}>Caminho documental</span><h3>Decisão, contrato e comprovantes.</h3><p>O documento deve permitir identificar a obrigação e os critérios. Arquivos complementares podem ser necessários para parcelas, pagamentos ou mudanças posteriores.</p><ul><li>Texto completo e legível da regra aplicável.</li><li>Valores relacionados aos respectivos documentos.</li><li>Lacunas identificadas antes do cálculo.</li></ul><p>Uma decisão em PDF nem sempre contém todos os dados financeiros necessários.</p></article><article style={{background:'#f1f7fa'}}><span className={s.label}>Caminho estruturado</span><h3>Valores organizados por parcela.</h3><p>A planilha prevista deve separar rubrica, valor original e datas, além dos registros necessários à conferência de pagamentos e abatimentos.</p><ul><li>Uma obrigação ou parcela por linha.</li><li>Marcos de incidência e data-base claros.</li><li>Conciliação com os documentos de origem.</li></ul><p>Uma planilha preenchida não dispensa a validação dos critérios escolhidos.</p></article></div></section>

    <section className={`${s.section} ${s.paper}`} id="como-funciona"><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>A entrega proposta</p><h2>Uma memória para ler,<br/>revisar e discutir.</h2><p className={s.lead}>O relatório em PDF previsto reúne resumo, premissas e evolução dos valores. Sua utilidade está em permitir conferir a conta, e não apenas exibir um total.</p><div className={s.copy}><h3>O uso continua com o responsável pelo caso.</h3><p>O documento não movimenta os autos, não realiza bloqueio pelo Sisbajud e não garante aceitação judicial. Protocolo, prazos e providências permanecem com os profissionais e canais responsáveis.</p><p>Antes da disponibilização do módulo, não envie peças ou dados do processo por esta página.</p></div></div><aside className={s.reportOutline} aria-label="Estrutura prevista do relatório"><p>Relatório · Estrutura prevista</p><ol><li><strong>Identificação e data-base</strong><span>Origem da obrigação e referência temporal do cálculo.</span></li><li><strong>Premissas e fontes</strong><span>Índices, taxas, períodos e bases utilizados.</span></li><li><strong>Memória por parcela</strong><span>Principal, incidências e abatimentos documentados.</span></li><li><strong>Resumo dos componentes</strong><span>Valores separados e composição do total.</span></li><li><strong>Pontos para revisão</strong><span>Informações incompletas e critérios a esclarecer.</span></li></ol></aside></div></section>
    <ServiceEnd page={page} faqTitle="Perguntas antes de atualizar os valores." title="Entender a evolução do valor começa por entender a regra." text="Conheça os serviços disponíveis enquanto o Relatório de Atualização Financeira é preparado. Escopo, formatos e condições serão informados antes da abertura de solicitações."/>
  </main>;
}
