import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd, ServiceHeroPhoto } from "./ServiceDetails";
import s from "./services.module.css";

export function ImportAuditPage({ page }: { page: ServicePage }) {
  return <main className={s.page} data-service="auditoria-de-importacao">
    <section className={`${s.importHero} ${s.dark} ${s.photoHero}`}><div className={s.wrap}><div className={s.photoGrid}><div><p className={s.kicker}>Auditoria de importação · Da mercadoria ao documento</p><h1>Inteligência artificial que busca<br/><em>isenções e Ex-tarifários para sua importação.</em></h1><p className={s.lead}>A proposta da IA Audita é cruzar a documentação técnica com as regras vigentes para identificar benefícios aplicáveis e apoiar a revisão da tributação antes do desembaraço.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#conferencia-documental">Ver o que será conferido ↓</a></div></div><ServiceHeroPhoto name="importacao" alt="Vista ilustrativa de um navio cargueiro entre contêineres e guindastes em um porto ao anoitecer." title="Da origem da carga à segurança da informação."/></div></div></section>


    <section className={`${s.heroSupport} ${s.dark}`}><div className={s.wrap}><div className={s.manifest} aria-label="Sequência da revisão de importação"><div><small>01 · EVIDÊNCIA</small><strong>Documentos comerciais</strong><p>Invoice e packing list</p></div><div><small>02 · IDENTIFICAÇÃO</small><strong>Produto e especificações</strong><p>Função, modelo e composição</p></div><div><small>03 · ENQUADRAMENTO</small><strong>NCM e tratamento fiscal</strong><p>Regras e vigência</p></div><div><small>04 · DECISÃO</small><strong>Cenários revisados</strong><p>Premissas e pontos pendentes</p></div></div></div></section>

    <section className={`${s.wrap} ${s.section}`} id="conferencia-documental"><div className={s.split}><div><p className={s.kicker}>Onde começa a conferência</p><h2>O mesmo produto.<br/>Descrito da mesma forma.</h2><p className={s.lead}>Uma diferença entre documentos pode chegar à classificação, aos valores declarados e ao planejamento da operação.</p></div><div className={s.copy}><h3>Invoice e packing list se complementam.</h3><p>A invoice registra dados comerciais. O packing list ajuda a identificar a composição física da carga. Quantidades, unidades, modelos e referências precisam ser conciliados, respeitando a finalidade de cada documento.</p><h3>O catálogo explica o que o nome não diz.</h3><p>Função, materiais, dimensões e características técnicas podem ser decisivos para distinguir mercadorias. Uma expressão genérica como “peças” ou “equipamento eletrônico” pode ser insuficiente.</p><h3>Tradução também exige conferência.</h3><p>Documentos em inglês, mandarim ou outro idioma devem preservar códigos, unidades e termos técnicos. Uma tradução de apoio precisa continuar vinculada ao original para permitir revisão.</p></div></div></section>

    <section className={`${s.section} ${s.paper}`} id="exemplos"><div className={s.wrap}><div className={s.split}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo fictício 01 · Documentos divergentes</span><h2>Cem unidades na invoice.<br/>Noventa no embarque?</h2><p style={{marginTop:25}}>Uma empresa prepara a importação de um equipamento. Ao comparar os documentos, encontra quantidade e modelo diferentes. Não está claro se houve embarque parcial ou erro de preenchimento.</p><h4>O que uma revisão deve esclarecer</h4><p>É preciso voltar ao fornecedor, confirmar os itens efetivamente embarcados e obter documentos coerentes. Alterar um número sem evidência apenas transfere a dúvida para a declaração.</p></article><div><div className={s.documentCompare}><div><h4>Commercial invoice</h4><dl><dt>Quantidade</dt><dd>100 unidades</dd><dt>Modelo</dt><dd>Equipamento A</dd><dt>Referência</dt><dd>Lote ilustrativo</dd></dl></div><div><h4>Packing list</h4><dl><dt>Quantidade</dt><dd><mark>90 unidades</mark></dd><dt>Modelo</dt><dd><mark>Equipamento B</mark></dd><dt>Referência</dt><dd>Lote ilustrativo</dd></dl></div></div><p className={s.note}>Dados inventados para demonstrar uma inconsistência documental. O esclarecimento depende dos documentos e das partes da operação.</p><ul className={s.checklist} style={{marginTop:25}}><li><strong>Confirmar o embarque</strong>Quais produtos e quantidades compõem a carga?</li><li><strong>Corrigir na origem</strong>As versões emitidas pelo fornecedor precisam refletir os fatos.</li><li><strong>Revisar antes de declarar</strong>Concilie a documentação com o profissional responsável.</li></ul></div></div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.sectionIntro}><p className={s.kicker}>Classificação e benefícios</p><h2>A NCM começa no produto.<br/>O benefício começa na regra.</h2></div><div className={s.cards}><article className={s.card}><span className={s.cardNumber}>01 · CLASSIFICAR</span><h3>Documente a hipótese.</h3><p>A classificação fiscal deve corresponder às características da mercadoria. Menor imposto não é justificativa suficiente para mudar o código. A descrição técnica sustenta a revisão.</p></article><article className={s.card}><span className={s.cardNumber}>02 · PESQUISAR</span><h3>Confira o tratamento vigente.</h3><p>Use fontes oficiais, como o Classif do Portal Único Siscomex, e verifique os atos aplicáveis. Descrição, condições e vigência precisam coincidir com a operação.</p></article><article className={s.card}><span className={s.cardNumber}>03 · VALIDAR</span><h3>Separe cada tributo.</h3><p>Um Ex-tarifário que modifica o Imposto de Importação não zera automaticamente IPI e demais tributos. Cada componente tem tratamento e base a conferir.</p></article></div><p className={s.note}>A proposta de auditoria organiza evidências e pontos de atenção. A classificação e o uso de benefícios exigem revisão especializada antes da declaração.</p></section>

    <section className={`${s.section} ${s.dark}`} id="exemplo-importacao"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Exemplo fictício 02 · Revisão tributária</p><h2>O impacto de uma revisão<br/>em uma carga de R$ 500 mil.</h2><p>Considere uma importação de componentes eletrônicos industriais vindos da China. A descrição comercial é genérica, mas a ficha técnica contém informações que podem mudar a análise do enquadramento.</p></div><div className={s.casePair}><article className={s.caseCopy}><span className={s.caseLabel}>Cenário inicial · Informação incompleta</span><h3>Uma descrição genérica deixa perguntas em aberto.</h3><p>A invoice identifica os itens apenas como componentes eletrônicos. Sem conferir função, composição e aplicação, não é possível concluir se o código adotado corresponde à mercadoria ou se há algum benefício aplicável.</p><ul><li><strong>Valor aduaneiro considerado:</strong> R$ 500.000.</li><li><strong>Ponto a esclarecer:</strong> a classificação precisa corresponder às especificações do produto.</li><li><strong>Documentos necessários:</strong> invoice original, catálogo e ficha técnica completa.</li></ul></article><article className={s.caseCopy}><span className={s.caseLabel}>Cenário de revisão · Proposta da IA Audita</span><h3>Da especificação técnica à pesquisa de benefícios.</h3><p>A revisão proposta relaciona a descrição da invoice às características técnicas e organiza os pontos de classificação para conferir NCM, eventuais isenções e Ex-tarifários vigentes.</p><ul><li><strong>Identificar o produto:</strong> função, modelo, materiais e aplicação.</li><li><strong>Conferir o benefício:</strong> descrição legal, condições e vigência.</li><li><strong>Validar o enquadramento:</strong> revisão especializada antes de utilizar o cenário tributário.</li></ul></article></div><div className={s.costBands}><article><span className={s.label}>Premissa didática · Base de IPI</span><strong>R$ 500.000</strong><p>Para isolar a conta, suponha II igual a zero e uma base de IPI de R$ 500.000. Essa hipótese não confirma isenção para a mercadoria.</p></article><article><span className={s.label}>Alíquota hipotética · 15%</span><strong>R$ 75.000</strong><p>R$ 500.000 × 15% = R$ 75.000 de IPI neste exemplo. A alíquota é apenas ilustrativa e não foi atribuída a uma NCM específica.</p></article></div><p className={s.note}>Na importação, a base do IPI considera o valor aduaneiro acrescido do Imposto de Importação. Um Ex-tarifário de II não reduz automaticamente a alíquota do IPI. Sem identificação técnica e fundamento aplicável, não é possível informar uma economia confirmada. Este cenário não representa resultado comprovado de cliente nem o custo total da operação.</p><a className={s.textLink} href="https://www4.receita.fazenda.gov.br/simulador/glossario.html" target="_blank" rel="noopener noreferrer">Conferir as bases de cálculo na Receita Federal ↗</a></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><div><p className={s.kicker}>Preparação da operação</p><h2>O que reunir<br/>antes da análise.</h2><p className={s.lead}>Versões completas e legíveis permitem comparar a informação. Arquivos sem páginas ou descrições incompletas deixam perguntas sem resposta.</p></div><ul className={s.checklist}><li><strong>Invoice e packing list</strong>Identificação das partes, mercadorias, valores, unidades, quantidades e volumes.</li><li><strong>Ficha técnica e catálogo</strong>Função, composição, modelo e especificações do produto, com o documento original.</li><li><strong>Informações logísticas e comerciais</strong>Condições negociadas, origem, frete, seguro e documentos pertinentes à formação dos valores.</li><li><strong>Hipóteses fiscais anteriores</strong>NCM utilizada, atos e fundamentos pesquisados, dúvidas e orientações já recebidas.</li></ul></div></section>

    <section className={`${s.section} ${s.paper}`} id="como-funciona"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Fluxo previsto do serviço</p><h2>Conferir, explicar<br/>e encaminhar para revisão.</h2><p>O recebimento de documentos ainda não está habilitado. Estes são os objetivos da análise proposta, sujeitos ao escopo informado na disponibilização.</p></div><ol className={s.steps}><li><h3>Organizar a entrada</h3><p>Relacionar documentos à mesma operação e identificar versões e lacunas.</p></li><li><h3>Cruzar informações</h3><p>Comparar descrição, quantidade, identificação e valores documentados.</p></li><li><h3>Examinar hipóteses</h3><p>Estruturar os pontos de classificação e tributação com suas referências.</p></li><li><h3>Explicar o resultado</h3><p>Apresentar inconsistências e cenários com premissas claras para validação responsável.</p></li></ol><p className={s.note}>A revisão não determina canal aduaneiro, prazo de liberação ou dispensa de fiscalização. Armazenagem e outros custos dependem da operação.</p></div></section>
    <ServiceEnd page={page} faqTitle="Perguntas de quem prepara uma importação." title="Uma importação bem preparada começa antes da declaração." text="Organize os documentos da operação e conheça a proposta de auditoria. Consulte a disponibilidade antes de encaminhar arquivos."/>
  </main>;
}
