import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd, ServiceHeroPhoto } from "./ServiceDetails";
import s from "./services.module.css";

export function IncomeTaxPage({ page }: { page: ServicePage }) {
  return <main className={s.page} data-service="isencao-imposto-de-renda">
    <section className={`${s.irHero} ${s.dark} ${s.photoHero}`}><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>Lei nº 7.713/88</p><h1>Isenção de<br/><em>Imposto de Renda.</em></h1><p className={s.lead}><strong>Você pode ter direito a parar de pagar IR sobre sua aposentadoria ou pensão.</strong></p><p className={s.lead}>A Lei nº 7.713/88 prevê a isenção para pessoas com doenças e condições definidas em lei, sobre rendimentos elegíveis. Se houve pagamento indevido, também é possível avaliar a restituição, conforme os documentos, as datas e os prazos de cada caso.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#doencas">Veja as doenças e condições ↓</a></div></div><ServiceHeroPhoto name="ir" alt="Cena ilustrativa de uma mulher idosa conversando com uma familiar à mesa." title="Mais tranquilidade para cuidar do que importa."/></div></section>


    <section className={`${s.wrap} ${s.section}`} id="historico-de-cancer"><p className={s.kicker}>Atenção, aposentados e pensionistas</p><h2>Você tem histórico de câncer?<br/><em>Confira seu direito à isenção.</em></h2><p className={s.lead}>A Lei nº 7.713/88 garante a isenção do Imposto de Renda sobre aposentadoria ou pensão para pessoas com neoplasia maligna (câncer), observados os requisitos legais e a comprovação da doença.</p><p className={s.lead}><strong>Se você continuou pagando imposto após o diagnóstico, pode ter direito a receber de volta valores dos últimos 5 anos.</strong> A restituição depende do início do direito à isenção, dos valores pagos indevidamente e dos prazos aplicáveis a cada exercício.</p><p className={s.note}>O histórico da doença pode dar direito à isenção mesmo sem sintomas atuais. Confira os documentos e o período elegível antes de solicitar a revisão. <a className={s.textLink} href="https://www.gov.br/pgfn/pt-br/cidadania-tributaria/por-assunto/imposto-de-renda-pessoa-fisica-irpf-2/isencao-por-molestia-grave">Consultar orientação oficial ↗</a></p></section>

    <section className={`${s.section} ${s.paper}`} id="doencas"><div className={`${s.wrap} ${s.split}`}><div><p className={s.kicker}>Lei nº 7.713/88 · Artigo 6º, inciso XIV</p><h2>O rol de condições e doenças<br/><em>que podem dar direito à isenção.</em></h2><div className={s.copy}><p style={{marginTop:24}}>A Lei nº 7.713/88 estabelece um rol de patologias e condições para a isenção do Imposto de Renda. O direito depende do enquadramento legal, da comprovação e da natureza do rendimento. Confira a relação e observe os qualificadores “ativa”, “grave” e “irreversível e incapacitante”.</p><p>Neoplasia maligna, por exemplo, merece conferência mesmo quando a pessoa está em acompanhamento e não apresenta sintomas atuais. A história clínica e as regras aplicáveis são relevantes.</p><p>Há situações específicas que exigem cuidado adicional: a Receita menciona Alzheimer quando comprovada alienação mental, cegueira inclusive monocular e síndrome da talidomida. Consulte a orientação oficial para o seu enquadramento.</p><a className={s.textLink} href="https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/perguntas-frequentes/imposto-de-renda/dirpf/deducoes/quais-doencas-podem-dar-isencao">Consultar as condições na Receita Federal ↗</a></div></div><div><h3>Doenças e condições previstas</h3><ul className={s.diseaseList}>{["Moléstia profissional","Tuberculose ativa","Alienação mental","Esclerose múltipla","Neoplasia maligna (câncer)","Cegueira, inclusive monocular","Hanseníase","Paralisia irreversível e incapacitante","Cardiopatia grave","Doença de Parkinson","Espondiloartrose anquilosante","Nefropatia grave","Hepatopatia grave","Doença de Paget em estado avançado","Contaminação por radiação","Síndrome da imunodeficiência adquirida (Aids)","Fibrose cística (mucoviscidose)"].map((item,index)=><li key={item}><strong>{String(index+1).padStart(2,"0")} · {item}</strong></li>)}</ul><p className={s.note}>AVC não equivale, por si só, a paralisia irreversível e incapacitante; LER/DORT exige avaliação do enquadramento como moléstia profissional. O inciso XIV também prevê aposentadoria ou reforma motivada por acidente em serviço. Para pensões, o inciso XXI exclui a hipótese de moléstia profissional.</p></div></div></section>

    <section className={`${s.wrap} ${s.section}`} id="requisitos"><div className={s.split}><div className={s.sectionIntro}><p className={s.kicker}>Quem deve conferir</p><h2>O direito depende da renda<br/>e da condição de saúde.</h2><p>O diagnóstico não torna toda a declaração isenta. A análise começa pela natureza de cada rendimento e pelo enquadramento documentado da condição.</p></div><aside className={s.taxCard} aria-label="Roteiro de verificação da isenção"><p>Antes de olhar o valor</p><h2>Três informações precisam se encontrar.</h2><dl><div><dt>01 · O benefício</dt><dd>Aposentadoria, pensão, reforma ou reserva remunerada.</dd></div><div><dt>02 · A condição de saúde</dt><dd>Enquadramento legal e comprovação adequada ao procedimento.</dd></div><div><dt>03 · A linha do tempo</dt><dd>Datas, retenções e declarações dos períodos analisados.</dd></div></dl><small>Este roteiro é informativo e não recebe documentos médicos.</small></aside></div><div className={s.eligibility}><article><span className={s.label}>Rendimento elegível</span><h3>A origem do dinheiro importa.</h3><p>Verifique os proventos de aposentadoria, pensão, reforma ou reserva. Complementações exigem atenção à modalidade. Salário, trabalho autônomo e aluguel não se tornam automaticamente isentos por causa do diagnóstico.</p></article><span aria-hidden="true">+</span><article><span className={s.label}>Condição prevista</span><h3>A comprovação também importa.</h3><p>É necessário verificar a hipótese legal e seus documentos. A palavra “grave” em um relatório, isoladamente, não define o direito. Datas e informações clínicas pertinentes precisam estar claras para o procedimento.</p></article></div></section>



    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><div><p className={s.kicker}>Duas análises diferentes</p><h2>Os próximos descontos.<br/>Os anos que já passaram.</h2><p className={s.lead}>Pedir o reconhecimento para os pagamentos futuros e revisar imposto anterior exige olhar para documentos diferentes.</p></div><div className={s.rows}><article><span>01</span><div><h3>Conferir a retenção daqui para frente</h3><p>Identifique a fonte pagadora e as exigências do pedido. Na via administrativa, a Receita orienta a obtenção de laudo de serviço médico oficial. Relatórios e exames particulares ajudam a documentar o histórico, mas não devem ser confundidos com esse laudo.</p></div></article><article><span>02</span><div><h3>Apurar o que foi pago anteriormente</h3><p>Compare as datas de elegibilidade com informes, declarações e restituições já recebidas. Eventual retificação e pedido de restituição dependem da apuração de cada exercício e dos prazos aplicáveis.</p></div></article><article><span>03</span><div><h3>Esclarecer uma negativa ou uma lacuna</h3><p>Uma resposta administrativa deve ser lida com os motivos apresentados. Documentação complementar ou avaliação jurídica pode ser necessária. Não há abertura automática de ação ou decisão de isenção pela IA Audita.</p></div></article></div></div></section>

    <section className={`${s.section} ${s.dark}`} id="exemplos"><div className={s.wrap}><p className={s.kicker}>Exemplo fictício 01 · Retenções documentadas</p><div className={s.split}><div className={s.caseCopy}><h2>Quanto foi retido<br/>não é, sozinho,<br/><em>quanto será restituído.</em></h2><p style={{marginTop:25}}>Uma aposentada reúne 12 comprovantes mensais com R$ 300 de IR em cada um. A soma ajuda a começar a conferência, mas ainda não é um crédito confirmado.</p></div><div><div className={s.equation}><div><strong>R$ 300</strong><small>por pagamento</small></div><span>×</span><div><strong>12</strong><small>pagamentos</small></div><span>=</span><div><strong>R$ 3.600</strong><small>retenções a conferir</small></div></div><p className={s.note}>Hipótese ilustrativa, sem 13º ou atualização. É preciso verificar o período elegível, o ajuste anual e o que já foi restituído. Não se deve multiplicar esse valor por cinco anos e tratá-lo como garantido.</p></div></div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><article className={s.caseCopy}><span className={s.caseLabel}>Exemplo fictício 02 · Rendimentos mistos</span><h2>Aposentadoria e aluguel<br/>na mesma declaração.</h2><p style={{marginTop:24}}>Uma pessoa com condição prevista em lei recebe aposentadoria e renda de um imóvel. Ela procura entender se pode deixar de recolher IR sobre tudo.</p><h4>O ponto decisivo</h4><p>O tratamento da aposentadoria não se estende automaticamente ao aluguel. Cada fonte deve ser identificada e classificada antes de recalcular a declaração.</p><h4>Como avançar</h4><p>Separar informes, comprovantes e datas para que a análise tributária considere a renda elegível e os demais rendimentos sem misturá-los.</p></article><div><p className={s.kicker}>A pasta que ajuda a esclarecer</p><ul className={s.checklist}><li><strong>Documentação do benefício</strong>Concessão, fonte pagadora e comprovantes dos pagamentos.</li><li><strong>Histórico médico pertinente</strong>Relatórios, exames e laudo oficial, conforme a exigência administrativa.</li><li><strong>Imposto por exercício</strong>Informes, declarações, recibos e restituições já recebidas.</li><li><strong>Pedidos anteriores</strong>Protocolos, respostas e eventuais exigências de complementação.</li></ul></div></div></section>

    <section className={`${s.section} ${s.paper}`} id="como-funciona"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Organização antes do pedido</p><h2>Uma sequência para avaliar seu caso.</h2></div><ol className={s.steps}><li><h3>Separe as fontes</h3><p>Identifique quais rendimentos são benefícios e quais têm outra natureza.</p></li><li><h3>Reúna a comprovação</h3><p>Organize os documentos médicos e as datas relevantes para o enquadramento.</p></li><li><h3>Confira o canal</h3><p>Verifique o procedimento da fonte pagadora. O módulo da IA Audita segue indisponível.</p></li><li><h3>Revise o passado</h3><p>Avalie os exercícios anteriores com apoio adequado, observando prazos e valores já restituídos.</p></li></ol><p className={s.note}>Se o titular faleceu, eventual revisão de períodos anteriores exige representação e documentação próprias. A isenção pessoal não é transferida aos herdeiros.</p></div></section>
    <ServiceEnd page={page} faqTitle="O que ainda precisa ser esclarecido sobre a isenção?" title="Entender o desconto é o primeiro passo para conferir seu direito." text="Guarde seus documentos em segurança. Consulte a disponibilidade do módulo antes de encaminhar dados de saúde ou contratar uma análise."/>
  </main>;
}
