import type { ServicePage } from "../../lib/service-pages";
import { ServiceAction, ServiceEnd, ServiceHeroPhoto } from "./ServiceDetails";
import s from "./services.module.css";

export function PisPasepPage({ page }: { page: ServicePage }) {
  return <main className={s.page} data-service="pis-pasep">
    <section className={`${s.pisHero} ${s.photoHero}`}><div className={`${s.wrap} ${s.split}`}>
      <div><p className={s.kicker}>PIS/Pasep · Cotas do antigo fundo</p><h1>O trabalho de uma vida<br/><em>merece uma nova consulta.</em></h1><p className={s.lead}>Você, seus pais ou seus avós trabalharam entre 1971 e 1988? A história profissional da família pode ajudar a localizar cotas ainda não sacadas. Entenda quem pode consultar e como preparar o pedido.</p><div className={s.actions}><ServiceAction page={page}/><a className={s.textLink} href="#titular-ou-herdeiro">Encontre o seu caminho ↓</a></div><p className={s.note}>Assistência documental privada e opcional. A consulta oficial é gratuita.</p></div>
      <ServiceHeroPhoto name="pis" alt="Cena ilustrativa de uma família reunida à mesa para conferir documentos antigos." title="Uma história de trabalho. Um cuidado de família."/>
    </div></section>


    <section className={s.timelineBand}><div className={s.wrap}><aside className={s.historyStrip} aria-label="Linha do tempo das cotas"><p>Uma história para reconstruir</p><div className={s.yearRange}>1971—1988</div><dl><div><dt>Antes</dt><dd>Trabalho com carteira assinada ou no serviço público, no período do antigo fundo.</dd></div><div><dt>Hoje</dt><dd>Consulta para verificar se existem cotas não sacadas e valores a ressarcir.</dd></div><div><dt>Família</dt><dd>Beneficiários legais também podem verificar a situação de um titular falecido.</dd></div></dl></aside></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><div><p className={s.kicker}>Antes de procurar um saldo</p><h2>Mesmo nome.<br/>Direitos diferentes.</h2></div><div className={s.copy}><p>As <strong>cotas do antigo fundo</strong> são diferentes do abono salarial. Elas estão relacionadas ao patrimônio acumulado em contas individuais do PIS/Pasep. A consulta busca identificar se ainda há valor não sacado referente a essa participação.</p><p>Já o <strong>abono salarial</strong> tem regras e calendário vinculados ao respectivo ano-base. Receber o abono hoje, ou não ter direito a ele, não responde à pergunta sobre cotas antigas.</p><p>Ter trabalhado no período é um motivo para conferir. A existência de saldo depende do histórico individual, inclusive de saques já realizados.</p></div></div><div className={s.freeCallout}><strong>Comece pela consulta gratuita.</strong><p>O <a className={s.textLink} href="https://repiscidadao.fazenda.gov.br/">REPIS Cidadão ↗</a> é o canal do Ministério da Fazenda para consultar as cotas. Havendo saldo, siga as instruções oficiais para solicitar o ressarcimento pela CAIXA. Contratar assistência não é requisito para usar esse serviço.</p></div></section>

    <section className={`${s.section} ${s.paper}`} id="titular-ou-herdeiro"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Dois pontos de partida</p><h2>Você consulta para si<br/>ou para alguém da família?</h2><p>O objetivo é o mesmo: esclarecer se há cotas a receber. A identificação de quem pode fazer o pedido muda o conjunto de documentos.</p></div><div className={s.pathway}>
      <article><span className={s.label}>01 · Titular</span><h3>Quero conferir meu próprio histórico.</h3><p>Comece pelos seus dados e pela inscrição PIS/Pasep. Carteiras de trabalho, registros funcionais e comprovantes antigos podem ajudar a esclarecer divergências, quando existirem.</p><ul><li>Confira nome, CPF e inscrição antes de concluir a consulta.</li><li>Verifique se o resultado informa saldo ou orienta alguma providência.</li><li>Guarde a resposta e os protocolos para acompanhar a solicitação.</li></ul><p>Um vínculo registrado comprova uma parte da história. Ele não demonstra, sozinho, que o valor continua disponível.</p></article>
      <article><span className={s.label}>02 · Beneficiário legal</span><h3>Quero consultar um titular falecido.</h3><p>A consulta e o pedido precisam respeitar a representação do titular. A condição de dependente ou sucessor deve ser comprovada pelos documentos aceitos no procedimento oficial.</p><ul><li>Reúna a identificação e a inscrição do titular falecido.</li><li>Separe certidão de óbito e documentação de dependência ou sucessão pertinente ao caso.</li><li>Confira as exigências para o pedido quando houver outros beneficiários.</li></ul><p>Use sua própria identificação nos canais que permitam a consulta de beneficiário. Não compartilhe senhas nem tente acessar a conta pessoal do falecido.</p></article>
    </div></div></section>

    <section className={`${s.wrap} ${s.section}`} id="como-funciona"><div className={s.sectionIntro}><p className={s.kicker}>Da lembrança ao documento</p><h2>Quatro passos para sair da dúvida.</h2></div><ol className={s.steps}><li><h3>Reconstrua o vínculo</h3><p>Identifique quem trabalhou no período e reúna os registros disponíveis. Se faltar uma informação, registre a lacuna para buscar orientação.</p></li><li><h3>Faça a consulta</h3><p>Confira o resultado no REPIS Cidadão. A resposta oficial é a referência para decidir o próximo passo.</p></li><li><h3>Prepare o pedido</h3><p>Havendo valor, siga os canais da CAIXA e apresente os documentos exigidos para titular ou beneficiário.</p></li><li><h3>Acompanhe</h3><p>Observe protocolos, complementações e calendário oficial. A consulta de saldo e a conclusão do pagamento são etapas distintas.</p></li></ol></section>

    <section className={`${s.section} ${s.dark}`} id="exemplos"><div className={s.wrap}><div className={s.sectionIntro}><p className={s.kicker}>Histórias possíveis</p><h2>A mesma consulta.<br/>Duas situações de família.</h2><p>Exemplos fictícios para explicar o procedimento, sem indicar saldo ou resultado de clientes.</p></div><div className={s.casePair}>
      <article className={s.caseCopy}><span className={s.caseLabel}>Exemplo 01 · Registros antigos</span><h3>A carteira de trabalho saiu da gaveta.</h3><p>Uma pessoa encontra os registros de uma empresa em que trabalhou de 1978 a 1985. Nunca conferiu as cotas e não se lembra de ter feito um saque.</p><h4>Como essa informação ajuda</h4><p>O documento permite organizar o histórico e conferir a inscrição. Depois, a consulta oficial indica se existe valor a ressarcir. A lembrança de não ter sacado não substitui essa verificação.</p><h4>O próximo passo</h4><p>Conferir os dados, consultar o REPIS e seguir a orientação do resultado. Se aparecer uma divergência, buscar esclarecimento no canal responsável.</p></article>
      <article className={s.caseCopy}><span className={s.caseLabel}>Exemplo 02 · Documentos da família</span><h3>Uma filha encontra o registro funcional do pai.</h3><p>Ao organizar documentos, a família encontra a inscrição de um servidor que trabalhou na década de 1980 e já faleceu. A filha quer saber se há valores antigos.</p><h4>O que precisa ser acrescentado</h4><p>Além da identificação do pai, é preciso conferir a documentação de quem pode requerer o ressarcimento. O parentesco, por si só, não resolve todas as exigências de representação.</p><h4>O próximo passo</h4><p>Consultar o procedimento para beneficiários legais e reunir os documentos exigidos. Questões de sucessão pendentes precisam de orientação própria.</p></article>
    </div></div></section>

    <section className={`${s.wrap} ${s.section}`}><div className={s.split}><div><p className={s.kicker}>Quando falta uma peça</p><h2>“Não apareceu saldo.”<br/>E agora?</h2><div className={s.copy}><p style={{marginTop:24}}>Confira primeiro se a consulta usou os dados corretos. Divergências cadastrais, dúvidas sobre a inscrição ou sobre um saque anterior devem ser esclarecidas pelo canal oficial.</p><p>Se os dados estiverem corretos e não houver valor, não é possível presumir um crédito escondido. Pesquisas de outros bens, depósitos e questões de herança seguem caminhos diferentes.</p></div></div><div><h3>Onde a assistência documental entra</h3><p className={s.note}>A IA Audita ajuda a organizar o caminho, sem se apresentar como órgão público ou concedente do benefício.</p><ul className={s.checklist} style={{marginTop:24}}><li><strong>Identificar o que você já tem</strong>Documentos do titular, registros profissionais e respostas anteriores.</li><li><strong>Separar o que falta esclarecer</strong>Dados divergentes, representação do beneficiário ou exigências de complementação.</li><li><strong>Preparar uma consulta mais organizada</strong>Informações e registros disponíveis para seguir as orientações oficiais.</li></ul></div></div></section>
    <ServiceEnd page={page} faqTitle="O que você quer saber sobre as cotas?" title="Uma história antiga pode merecer atenção hoje." text="Comece pelos documentos e pela consulta oficial. Se precisar de apoio para organizar o procedimento, conheça a assistência documental da IA Audita."/>
  </main>;
}
