import Image from "next/image";
import Link from "next/link";
import styles from "../page.module.css";

export const metadata = { title: "Home anterior", robots: { index: false, follow: false }, alternates: { canonical: "/" } };

const otherServices = [
  { title: "Dívidas bancárias", route: "dividas-bancarias", status: "Disponível na plataforma", audience: "Sua dívida com o banco virou uma bola de neve? Entenda os juros do cartão de crédito, do financiamento ou do empréstimo antes de negociar.", analysis: "Auditoria dos extratos e organização dos contratos para conferir juros, tarifas, pagamentos e evolução do saldo. Identificação de possíveis divergências e encargos que merecem avaliação, com comparação às referências de mercado quando aplicáveis.", delivery: "Relatório Técnico de Auditoria Financeira com estimativas, memória de cálculo e premissas para apoiar a renegociação e, quando necessário, a avaliação de uma ação revisional por advogado.", note: "O recálculo depende dos documentos e das regras aplicáveis ao contrato. A taxa média do Banco Central é uma referência, não um teto automático. Não há garantia de desconto ou de acordo." },
  { title: "Cotas antigas PIS/PASEP", route: "pis-pasep", status: "Disponível na plataforma", audience: "Você ou um familiar trabalhou com carteira assinada ou foi servidor público entre 1971 e 1988? Pode haver cotas antigas a consultar, inclusive por herdeiros de titulares falecidos.", analysis: "Orientação para a consulta pública gratuita no REPIS e conferência dos documentos do titular ou dos herdeiros. Organização das informações necessárias para acompanhar o pedido de ressarcimento.", delivery: "Documentação organizada e acompanhamento assistido das etapas e protocolos informados. Se a consulta inicial não localizar valores, consulte a equipe sobre a viabilidade de investigação complementar e de encaminhamento jurídico.", note: "Não é o abono salarial anual. A plataforma não consulta automaticamente saldos. Rastreamento avançado, pesquisa genealógica, planos e eventual atendimento pelo parceiro Inventarium dependem de confirmação de disponibilidade e contratação específica; honorários e condições de êxito devem constar do contrato." },
  { title: "Auditoria de contas de luz", route: "contas-de-luz", status: "Disponível em piloto", audience: "Para residências e empresas que querem entender a conta de energia, conferir cobranças e avaliar possíveis pedidos de revisão ou restituição.", analysis: "Conferência de consumo, bandeiras, tarifas, tributos e somas das faturas, quando existem dados e referências compatíveis. Organização do histórico para avaliação técnica de eventuais diferenças.", delivery: "Resumo da análise e requerimento para baixar. Você apresenta o pedido à distribuidora, registra o protocolo e conta com acompanhamento da equipe.", note: "Não há envio automático nem garantia de restituição. Créditos relacionados à exclusão do ICMS da base do PIS/Cofins têm regras próprias de destinação tarifária; não representam automaticamente um crédito individual para saque. Valores, períodos e eventual saldo exigem análise específica." },
  { title: "Consulta de imóveis", route: "consulta-imoveis", status: "Em homologação", audience: "Para quem procura informações imobiliárias e quer conhecer os canais de consulta disponíveis na plataforma.", analysis: "Módulo de busca de informações sobre imóveis, com canais e cobertura ainda em validação.", delivery: "A apresentação do módulo está disponível no aplicativo. A disponibilidade de cada consulta depende da conclusão da homologação.", note: "Ainda não anunciamos cobertura nacional, busca irrestrita ou resultado de consulta garantido." },
];

const upcomingServices = [
  { title: "Laudo para análise de exames", status: "Em desenvolvimento", description: "Serviço em construção. O escopo, as condições de uso e os entregáveis serão apresentados quando estiver disponível." },
  { title: "Laudo para atualização de processos judiciais", status: "Em desenvolvimento", description: "Serviço em construção. As funcionalidades e os documentos entregues serão detalhados no lançamento." },
];

export default function Home() {
  return <main className={styles.home}>
    <section className={styles.intro}>
      <div className={styles.brandSymbol} aria-hidden="true"><Image src="/images/audita-oficial-branca.png" alt="" width={800} height={600} priority /></div>
      <div className={styles.introCopy}>
        <p className={styles.label}>IA Audita · Inteligência a serviço das pessoas</p>
        <h1>Informação complexa.<br/><em>Entendimento simples.</em></h1>
        <p className={styles.lead}>Uma plataforma, diferentes formas de ajudar. Conectamos inteligência artificial avançada, organização documental e análise técnica para transformar informações complexas e dispersas em conhecimento claro, acessível e decisivo.</p>
        <div className={styles.introActions}><a href="#sobre" className={styles.button}>Conheça a IA Audita ↓</a><a href="#servicos" className={styles.textLink}>Explore nossas soluções ↗</a></div>
      </div>
      <div className={styles.brandStatement}><span>Documentos. Contexto. Clareza.</span><p>Diferentes necessidades.<br/>O mesmo propósito: ajudar você a entender.</p></div>
    </section>
    <section id="servicos" className={styles.services}>
      <div className={styles.sectionHead}><p className={styles.label}>Nossos serviços</p><h2>O que você precisa<br/>entender melhor hoje?</h2><p>Diferentes necessidades. O mesmo propósito: ajudar você a entender. Escolha a análise para o seu momento e confira a disponibilidade de cada solução na plataforma.</p></div>
      <article id="importacao" className={`${styles.catalogItem} ${styles.importation}`}>
        <div><p className={styles.availability}>Importação · Solução em preparação</p><h3>Inteligência fiscal<br/>antes do desembaraço.</h3><p>IA Audita na importação e otimização da TIPI: uma proposta para transformar documentos operacionais em informação útil para despachantes e importadores.</p></div>
        <div><p>Da leitura da Invoice e do Packing List à auditoria de benefícios fiscais e Ex-Tarifários, a solução foi pensada para apoiar decisões antes do registro da DI/Duimp.</p><details className={styles.details}><summary>Conheça a proposta da solução</summary><dl><dt>Leitura inteligente</dt><dd>Extração e tradução de dados técnicos de documentos, inclusive em inglês ou mandarim, para reduzir a digitação manual.</dd><dt>Classificação NCM/TIPI</dt><dd>Sugestão de enquadramento conforme as características do produto e a tabela aplicável, com revisão da classificação fiscal.</dd><dt>Benefícios fiscais e Ex-Tarifários</dt><dd>Pesquisa de reduções e isenções para bens de capital e informática, sujeitas aos requisitos de cada benefício.</dd><dt>Compliance preventivo</dt><dd>Conferência dos dados e tributos antes do registro, buscando reduzir inconsistências, retrabalho e custos de armazenagem.</dd></dl><p className={styles.limit}>Escopo e integrações em validação. O serviço não está anunciado como disponível para contratação e não garante alíquota mínima, isenção, ausência de multas ou canal de desembaraço.</p></details></div>
      </article>
      <article id="assistente-ia" className={styles.catalogItem}>
        <div><p className={styles.availability}>Inteligência artificial</p><h3>Um assistente para ler,<br/>criar e entender.</h3><p>Além dos módulos especializados, converse com a IA Audita para organizar ideias, esclarecer dúvidas e trabalhar com informações do dia a dia.</p><a href="https://app.auditainteligente.com.br/chat" className={styles.textLink}>Conhecer o assistente ↗</a></div>
        <div><dl><dt>Leitura e interpretação</dt><dd>Apoio à leitura de PDFs e imagens, com identificação de cláusulas, datas, valores e pontos de atenção, conforme os formatos e recursos disponíveis.</dd><dt>Linguagem simples</dt><dd>Resumos de documentos, contratos, faturas, certidões e processos para facilitar a compreensão de termos técnicos, financeiros e jurídicos.</dd><dt>Criação e uso geral</dt><dd>Textos, traduções, sínteses, planejamentos, cálculos e rascunhos de relatórios, minutas e e-mails a partir da sua solicitação.</dd></dl><p className={styles.limit}>Confira as respostas e os documentos gerados. A IA pode cometer erros e não substitui a revisão de um profissional quando necessária.</p></div>
      </article>
      <article className={styles.service}><div className={styles.serviceImage}><Image src="/images/risco-compra-popular.webp" fill sizes="(max-width: 800px) 100vw, 45vw" alt="Documentos e chaves de uma negociação imobiliária" /></div><div className={styles.serviceCopy}><p className={styles.label}>Certidões e due diligence imobiliária</p><h3>Antes de assinar,<br/>conheça quem vende.</h3><p>Certidões do vendedor ajudam a identificar processos, dívidas e situações que merecem atenção antes de uma negociação. Organize a documentação e entenda o que precisa ser esclarecido.</p><ul><li>Certidões criminal e cível</li><li>Certidão de falência e recuperação</li><li>Certidão especial cível e criminal</li><li>PDFs oficiais organizados para sua conferência</li></ul><p>Escopo atualmente anunciado: quatro certidões do TJDFT para pessoa física no Distrito Federal. A investigação ampliada de pessoas físicas e jurídicas depende da disponibilidade de cada fonte.</p><Link href="/analise-de-vendedor" className={styles.textLink}>Conhecer a análise de vendedor ↗</Link></div></article>
      <details className={styles.details}><summary>Entenda os dois pilares da investigação imobiliária</summary><div className={styles.diligence}>
        <div><h4>Certidões do vendedor</h4><p>Uma diligência ampliada pode envolver distribuição cível estadual e federal, execuções fiscais, regularidade perante a Receita Federal, ações trabalhistas no TRT, CNDT, protestos, falência e recuperação judicial e processos criminais.</p><p>O objetivo é reunir elementos para avaliar riscos da negociação, inclusive situações que exijam análise jurídica de possível fraude à execução ou contra credores.</p></div>
        <div><h4>Certidões do imóvel urbano ou rural</h4><p>Ônus reais e ações reipersecutórias, cadeia vintenária, débitos de IPTU ou ITR, situação enfiteútica e débitos condominiais. Para imóveis rurais, também podem ser relevantes CCIR, SIGEF/INCRA, CAR e embargos ambientais.</p><p>A análise do histórico de proprietários e dos vínculos societários pode ajudar a levantar pontos de atenção sobre transferências patrimoniais.</p></div>
      </div><p>Esse é o escopo de referência para a expansão da due diligence, não uma lista de consultas já incluídas no serviço atual. Certidões incluídas em planos, auditoria avançada e taxas de cartórios devem ser confirmadas antes da contratação. A ausência de processos não significa risco zero.</p></details>
<article className={`${styles.service} ${styles.reverse}`}><div className={styles.serviceImage}><Image src="/images/hero-cobrancas-indevidas.png" fill sizes="(max-width: 800px) 100vw, 45vw" alt="Mulher revisando suas faturas e extratos bancários" /></div><div className={styles.serviceCopy}><p className={styles.label}>Bancário · Cobranças indevidas</p><h3>Seu dinheiro merece<br/>uma conferência cuidadosa.</h3><p>Encontrou um seguro que não reconhece? A análise de cobranças indevidas em contas e cartões Itaú ajuda a localizar lançamentos e organizar provas documentais, inclusive em históricos de faturas antigas.</p><ul><li>Leitura assistida de faturas e extratos, lançamento por lançamento</li><li>Conferência dos seguros e tarifas que você reconhece ou contesta</li><li>Organização dos valores, datas e documentos de origem</li><li>Dossiê e relatório técnico em PDF para avaliar os próximos passos</li></ul><details className={styles.details}><summary>Ressarcimento, atualização e alcance da análise</summary><p>A proposta contempla a análise de cartões administrados pelo Itaú, incluindo marcas parceiras. Consulte a cobertura do seu cartão e a disponibilidade para contas de outros bancos antes de iniciar.</p><p>O acordo coletivo do caso Itaú e uma eventual medida judicial têm regras próprias. A comparação entre restituição simples ou em dobro, juros e correção depende do enquadramento do caso e das premissas de cálculo. Danos morais e outros pedidos não são resultados automáticos.</p><p>O relatório apoia sua avaliação e eventual orientação jurídica. Não garante ressarcimento nem ajuíza processos automaticamente.</p></details><Link href="/analise-cobrancas-indevidas" className={styles.textLink}>Conhecer a análise de cobranças ↗</Link></div></article>
      <div className={styles.catalog}>
        <div className={styles.catalogIntro}><p className={styles.label}>Conheça também</p><h3>Mais serviços para situações<br/>que fazem parte da sua vida.</h3><p>Os serviços abaixo têm acesso pelo aplicativo, mesmo sem uma página comercial própria. É necessário fazer login para utilizar a plataforma.</p></div>
        {otherServices.map(service => <article key={service.route} id={service.route} className={styles.catalogItem}>
          <div><p className={styles.availability}>{service.status}</p><h4>{service.title}</h4><p>{service.audience}</p><a href={`https://app.auditainteligente.com.br/#${service.route}`} className={styles.textLink}>{service.status === "Em homologação" ? "Ver disponibilidade no aplicativo" : "Acessar serviço no aplicativo"} ↗</a></div>
          <div><dl><dt>O que o serviço analisa</dt><dd>{service.analysis}</dd><dt>O que você recebe</dt><dd>{service.delivery}</dd></dl><p className={styles.limit}>{service.note}</p></div>
        </article>)}
      </div>
      <article id="isencao-ir" className={styles.catalogItem}><div><p className={styles.availability}>Benefícios e tributos · Temporariamente indisponível</p><h3>Isenção e restituição de IR</h3><p>Uma proposta de apoio a aposentados, pensionistas e militares na reserva ou reforma que precisam entender a possibilidade de isenção por moléstia grave.</p></div><div><dl><dt>Triagem e documentação</dt><dd>Organização de laudos e comprovantes para avaliação das condições previstas na Lei nº 7.713/88, art. 6º, XIV, inclusive casos de neoplasia maligna.</dd><dt>Avaliação dos próximos passos</dt><dd>Análise profissional da possibilidade de cessar retenções e requerer restituição de períodos anteriores, observados os requisitos, as datas e os prazos aplicáveis.</dd></dl><p className={styles.limit}>O benefício não abrange automaticamente rendimentos do trabalho na ativa. A proposta contempla beneficiários do INSS e de regimes próprios. O módulo ainda não está habilitado para novas solicitações; não há promessa de isenção imediata ou restituição automática de cinco anos.</p></div></article>
      <div className={styles.roadmap}><h3>Laudos em desenvolvimento</h3><p>Também fazem parte do catálogo da IA Audita, mas ainda não estão disponíveis para novas solicitações.</p><div className={styles.roadmapItems}>{upcomingServices.map(service => <article key={service.title}><span>{service.status}</span><h4>{service.title}</h4><p>{service.description}</p></article>)}</div></div>
      <div className={styles.central}><h3>Central de atendimento e plataforma</h3><p>O acesso aos serviços exige login. Consulte a disponibilidade, os documentos necessários e as condições de cada análise na Central de Serviços.</p><nav aria-label="Atalhos dos serviços"><a href="https://app.auditainteligente.com.br/#dividas-bancarias">Dívidas bancárias ↗</a><a href="https://app.auditainteligente.com.br/#pis-pasep">Cotas antigas PIS/PASEP ↗</a><a href="#isencao-ir">Isenção e restituição de IR — disponibilidade</a><a href="https://app.auditainteligente.com.br/#contas-de-luz">Auditoria de contas de luz ↗</a><a href="https://app.auditainteligente.com.br/#consulta-imoveis">Consulta de imóveis ↗</a></nav></div>
    </section>
    <section id="sobre" className={styles.about}><div><p className={styles.label}>Sobre a IA Audita</p><h2>Tecnologia para ler.<br/>Clareza para decidir.</h2></div><div><p>Acreditamos que entender documentos não deveria ser um obstáculo para tomar boas decisões. A IA Audita combina automação inteligente, organização documental e metodologias de triagem e conferência para destacar exatamente o que merece sua atenção.</p><p>Reunir certidões, auditar cobranças, analisar contratos e estruturar relatórios técnicos de auditoria financeira: diferentes formas de transformar burocracia em informação útil, conforme o escopo de cada solução.</p><p>Da análise prévia do vendedor de um imóvel à conferência de cartões, extratos e faturas de energia, nosso compromisso vai além da tecnologia: leitura facilitada, documentos organizados e uma visão clara dos próximos passos.</p><p className={styles.disclaimer}>A análise depende dos documentos e das fontes disponíveis. Não garante ausência de riscos, redução de dívidas ou ressarcimento e não substitui orientação jurídica quando necessária.</p></div></section>
    <section className={styles.closing}><p className={styles.label}>Seu próximo passo começa com informação</p><h2>Olhe com mais atenção.<br/>Decida com mais clareza.</h2><a className={styles.button} href="https://app.auditainteligente.com.br/#central-servicos">Conhecer a plataforma ↗</a></section>
    <footer className={styles.footer}><div><strong>IA Audita</strong><p>Inteligência para as decisões da vida.</p></div><nav aria-label="Links institucionais"><Link href="/#servicos">Serviços</Link><Link href="/politica-de-privacidade">Privacidade</Link><Link href="/termos-de-uso">Termos de uso</Link></nav><small>© {new Date().getFullYear()} IA Audita</small></footer>
  </main>;
}
